###############################################################################
# 1_vent_plancia.yaml — Plancia Lovelace: Ventilazione naturale estiva (V2)
# Allineata all'ultimo 1_vent.yaml e ai sensori canonici di 0_sensors.yaml
#  - Temperature:  sensor.t_out, sensor.t_in_media
#  - Umidità ass.: sensor.ah_out, sensor.ah_in
#  - KPI vent:     sensor.vent_deltaT_in_out, sensor.vent_deltaAH_in_out
#  - Logiche:      binary_sensor.vent_recommend_open / _close, vent_flag_estate,
#                  vent_night_flush_now; input_* per soglie/override/notifiche
###############################################################################

views:
  - title: "1 · Ventilazione"
    path: vent
    icon: mdi:window-open-variant
    type: sections
    max_columns: 3

    sections:
      # ===============================================================
      # COLONNA 1 — STATO & COMANDI
      # ===============================================================
      - type: grid
        cards:

          # ---- CHIP DI STATO (glance) ---------------------------------
          - type: glance
            title: "Stato attuale"
            columns: 4
            entities:
              - entity: binary_sensor.vent_recommend_open
                name: APRI
                icon: mdi:window-open
              - entity: binary_sensor.vent_recommend_close
                name: CHIUDI
                icon: mdi:window-closed-variant
              - entity: binary_sensor.vent_flag_estate
                name: Estate
                icon: mdi:white-balance-sunny
              - entity: binary_sensor.vent_night_flush_now
                name: Night Flush
                icon: mdi:weather-night

          # ---- COMANDI RAPIDI -----------------------------------------
          - type: entities
            title: "Comandi rapidi"
            show_header_toggle: false
            entities:
              - entity: input_boolean.vent_override_estate
                name: "Override estate (forza logiche estive)"
                icon: mdi:calendar-range
              - entity: input_boolean.vent_notifiche_attive
                name: "Notifica consigli (persistenti)"
                icon: mdi:message-badge
              - type: section
                label: "Finestre (mappatura manuale)"
              - entity: input_boolean.vent_finestra_giorno_aperta
                name: "Giorno — finestra aperta"
                icon: mdi:window-open
              - entity: input_boolean.vent_finestra_notte1_aperta
                name: "Notte1 — finestra aperta"
                icon: mdi:window-open
              - entity: input_boolean.vent_finestra_notte2_aperta
                name: "Notte2 — finestra aperta"
                icon: mdi:window-open
              - entity: input_boolean.vent_finestra_notte3_aperta
                name: "Notte3 — finestra aperta"
                icon: mdi:window-open
              - entity: input_boolean.vent_finestra_bagno_aperta
                name: "Bagno — finestra aperta"
                icon: mdi:window-open

          # ---- MESSAGGIO CONSIGLIO ------------------------------------
          - type: markdown
            title: "Consiglio"
            content: >-
              {{ states('input_text.vent_messaggio_consiglio') }}

          # ---- COME DECIDE (spiegazione umana) ------------------------
          - type: markdown
            title: "Come decide"
            content: |
              **Logica estiva (maggio–settembre) — Ventilazione naturale**

              **APRI** (preferibilmente in *night flush* 21:00–08:00) se **T_out < T_in − ΔT_min**
              **e** **AH_out < AH_in − ΔAH_min**, **senza pioggia**, **vento ≤ soglia** e qualità aria OK.

              **CHIUDI** negli altri casi (o se **T_out ≥ T_in** o **AH_out ≥ AH_in**).

              **Default** soglie: ΔT_min **1.5 °C**, ΔAH_min **1.0 g/m³**, Vento_max **6.0 m/s**.

              *Obiettivo*: massimizzare il raffrescamento passivo notturno, riducendo l’uso dell’AC e
              evitando apporti di umidità.

      # ===============================================================
      # COLONNA 2 — KPI PRINCIPALI (mini-graph 24h)
      # ===============================================================
      - type: grid
        cards:

          # ---- KPI Temperatura ---------------------------------------
          - type: entities
            title: "KPI — Temperatura"
            entities:
              - entity: sensor.t_out
                name: "T out (°C)"
                icon: mdi:thermometer
              - entity: sensor.t_in_media
                name: "T in media (°C)"
                icon: mdi:home-thermometer
              - entity: sensor.vent_deltaT_in_out
                name: "ΔT (in − out) (°C)"
                icon: mdi:thermometer-lines

          - type: custom:mini-graph-card
            name: "T in/out — 24h"
            hours_to_show: 24
            points_per_hour: 6
            show:
              fill: false
              legend: true
              labels: false
            entities:
              - entity: sensor.t_out
                name: T out
              - entity: sensor.t_in_media
                name: T in (media)

          # ---- KPI Umidità assoluta ----------------------------------
          - type: entities
            title: "KPI — Umidità assoluta"
            entities:
              - entity: sensor.ah_out
                name: "AH out (g/m³)"
                icon: mdi:water-percent
              - entity: sensor.ah_in
                name: "AH in (g/m³)"
                icon: mdi:water-percent
              - entity: sensor.vent_deltaAH_in_out
                name: "ΔAH (in − out) (g/m³)"
                icon: mdi:water-minus

          - type: custom:mini-graph-card
            name: "AH in/out — 24h"
            hours_to_show: 24
            points_per_hour: 6
            show:
              fill: false
              legend: true
              labels: false
            entities:
              - entity: sensor.ah_out
                name: AH out
              - entity: sensor.ah_in
                name: AH in

          # ---- Meteo operativo ---------------------------------------
          - type: entities
            title: "Meteo operativo"
            entities:
              - entity: sensor.vent_meteo_vento
                name: "Vento (m/s)"
                icon: mdi:weather-windy
              - entity: binary_sensor.vent_pioggia
                name: "Pioggia"
                icon: mdi:weather-pouring
              - entity: binary_sensor.vent_air_quality_ok
                name: "Qualità aria OK"
                icon: mdi:chemical-weapon
              - entity: sensor.vent_meteo_pm25
                name: "PM2.5 (µg/m³)"
                icon: mdi:molecule

      # ===============================================================
      # COLONNA 3 — TREND / LOCK / SOGLIE
      # ===============================================================
      - type: grid
        cards:

          # ---- Trend estesi (7 giorni) --------------------------------
          - type: statistics-graph
            title: "Trend 7 giorni — T e AH"
            days_to_show: 7
            stat_types:
              - mean
              - min
              - max
            chart_type: line
            entities:
              - entity: sensor.t_out
                name: T out
              - entity: sensor.t_in_media
                name: T in (media)
              - entity: sensor.ah_out
                name: AH out
              - entity: sensor.ah_in
                name: AH in

          # ---- Soglie regolabili -------------------------------------
          - type: entities
            title: "Soglie & stato finestre"
            show_header_toggle: false
            entities:
              - entity: input_number.vent_deltat_min
                name: "ΔT_min per APRI (°C)"
                icon: mdi:tune-vertical
              - entity: input_number.vent_deltaah_min
                name: "ΔAH_min per APRI (g/m³)"
                icon: mdi:tune-vertical
              - entity: input_number.vent_vento_max
                name: "Vento massimo (m/s)"
                icon: mdi:turbine
              - entity: input_number.vent_pm25_max
                name: "PM2.5 massimo (µg/m³)"
                icon: mdi:blur
              - type: divider
              - entity: sensor.vent_finestre_aperte
                name: "Finestre aperte"
                icon: mdi:counter
              - entity: sensor.vent_finestre_state
                name: "Dettaglio finestre"
                icon: mdi:format-list-text
              - type: section
                label: "Ultimi cambi manuali"
              - entity: input_datetime.vent_last_change_giorno
                name: "Cambio zona giorno"
                icon: mdi:clock-outline
              - entity: input_datetime.vent_last_change_notte1
                name: "Cambio notte 1"
                icon: mdi:clock-outline
              - entity: input_datetime.vent_last_change_notte2
                name: "Cambio notte 2"
                icon: mdi:clock-outline
              - entity: input_datetime.vent_last_change_notte3
                name: "Cambio notte 3"
                icon: mdi:clock-outline
              - entity: input_datetime.vent_last_change_bagno
                name: "Cambio bagno"
                icon: mdi:clock-outline

          # ---- Debug sensori (grezzi/canonici) ------------------------
          - type: entities
            title: "Debug sensori"
            collapsible: true
            entities:
              # Canonici 0_sensors
              - entity: sensor.t_out
                name: "T out (canonico)"
              - entity: sensor.t_in_media
                name: "T in media (canonico)"
              - entity: sensor.ah_out
                name: "AH out (canonico)"
              - entity: sensor.ah_in
                name: "AH in (canonico)"
              # REST/meteo 1_vent
              - entity: sensor.vent_meteo_temp
                name: "REST — T out"
              - entity: sensor.vent_meteo_rh
                name: "REST — UR out"
              - entity: sensor.vent_meteo_vento
                name: "REST — vento"
              - entity: sensor.vent_meteo_precip
                name: "REST — pioggia"
