title: "1 — Ventilazione"
icon: mdi:fan
views:
  - title: "VMC"
    icon: mdi:fan-auto
    path: vmc
    cards:
      - type: entities
        title: "Stato generale VMC"
        show_header_toggle: false
        entities:
          - entity: sensor.vmc_priority
            name: Priorità
          - entity: sensor.vmc_reason
            name: Motivo corrente
          - entity: binary_sensor.vmc_failsafe_sensors_bad
            name: Failsafe sensori
          - entity: sensor.vmc_freecooling_status
            name: Stato freecooling
          - entity: sensor.vmc_vel_target
            name: Velocità target
          - entity: sensor.vmc_vel_index
            name: Indice velocità
          - entity: binary_sensor.vmc_bagno_boost_auto
            name: Boost bagno automatico
          - entity: binary_sensor.vmc_freecooling_candidate
            name: Candidato freecooling
          - entity: binary_sensor.vmc_anti_secco
            name: Anti-secco attivo

      - type: entities
        title: "Comandi manuali VMC"
        show_header_toggle: false
        entities:
          - entity: input_select.vmc_mode
            name: Modalità VMC
          - entity: input_select.vmc_manual_speed
            name: Velocità manuale
          - entity: input_boolean.vmc_manual
            name: Manuale attivo
          - entity: input_boolean.vmc_boost_bagno
            name: Boost bagno manuale
          - entity: input_number.vmc_bagno_on
            name: Soglia UR boost bagno ON
          - entity: input_number.vmc_bagno_off
            name: Soglia UR boost bagno OFF
          - entity: input_number.vmc_freecooling_delta
            name: Delta °C freecooling
          - entity: input_number.vmc_freecooling_delta_ah
            name: Delta AH freecooling
          - entity: input_number.vmc_anti_secco_ur_min
            name: UR minima anti-secco
          - entity: input_number.vent_deltat_min
            name: DeltaT minimo
          - entity: input_number.vent_deltaah_min
            name: DeltaAH minimo
          - entity: input_number.vent_vento_max
            name: Vento massimo
          - entity: input_number.vent_pm25_max
            name: PM2.5 massimo

      - type: entities
        title: "KPI ΔT / ΔAH"
        show_header_toggle: false
        entities:
          - entity: sensor.delta_t_in_out
            name: ΔT (interno-esterno)
          - entity: sensor.delta_ah_in_out
            name: ΔAH (interno-esterno)
          - entity: binary_sensor.vent_deltat_ok
            name: ΔT ok
          - entity: binary_sensor.vent_deltaah_ok
            name: ΔAH ok
          - entity: sensor.vent_ah_in
            name: AH interno
          - entity: sensor.vent_ah_out
            name: AH esterno

      - type: entities
        title: "Meteo e aria esterna"
        show_header_toggle: false
        entities:
          - entity: sensor.vent_meteo_temp
            name: Temperatura esterna
          - entity: sensor.vent_meteo_rh
            name: Umidità esterna
          - entity: binary_sensor.vent_pioggia
            name: Pioggia
          - entity: sensor.vent_meteo_vento
            name: Vento
          - entity: binary_sensor.vent_vento_blocco
            name: Blocco per vento
          - entity: sensor.vent_meteo_pm25
            name: PM2.5 esterno
          - entity: binary_sensor.vent_air_quality_ok
            name: Qualità aria ok
          - entity: sensor.vent_weather_label
            name: Condizione meteo

      - type: entities
        title: "Consigli e notifiche"
        show_header_toggle: false
        entities:
          - entity: input_text.vent_messaggio_consiglio
            name: Messaggio corrente
          - entity: input_boolean.vent_notifiche_attive
            name: Notifiche attive

  - title: "Finestre"
    icon: mdi:window-open-variant
    path: windows
    cards:
      - type: entities
        title: "Stato finestre"
        show_header_toggle: false
        entities:
          - entity: input_boolean.vent_finestra_giorno1_aperta
            name: Finestra giorno 1
          - entity: input_boolean.vent_finestra_giorno2_aperta
            name: Finestra giorno 2
          - entity: input_boolean.vent_portoncino_ingresso_aperto
            name: Portoncino ingresso
          - entity: input_boolean.vent_foro_cappa_aperto
            name: Foro cappa
          - entity: input_boolean.vent_finestra_notte1_aperta
            name: Finestra notte 1
          - entity: input_boolean.vent_finestra_notte2_aperta
            name: Finestra notte 2
          - entity: input_boolean.vent_finestra_notte3_aperta
            name: Finestra notte 3
          - entity: input_boolean.vent_finestra_bagno_aperta
            name: Finestra bagno

      - type: entities
        title: "KPI aperture"
        show_header_toggle: false
        entities:
          - entity: sensor.vent_finestre_aperte
            name: Finestre aperte
          - entity: sensor.vent_finestre_state
            name: Stato complessivo

      - type: entities
        title: "Suggerimenti ventilazione naturale"
        show_header_toggle: false
        entities:
          - entity: binary_sensor.vent_recommend_open
            name: Consiglio aprire
          - entity: binary_sensor.vent_recommend_close
            name: Consiglio chiudere
          - entity: binary_sensor.clima_open_windows_recommended
            name: Aprire finestre raccomandato

      - type: entities
        title: "Meteo rilevante"
        show_header_toggle: false
        entities:
          - entity: sensor.vent_meteo_vento
            name: Vento
          - entity: binary_sensor.vent_vento_blocco
            name: Blocco per vento
          - entity: binary_sensor.vent_pioggia
            name: Pioggia
          - entity: sensor.vent_meteo_pm25
            name: PM2.5 esterno
          - entity: binary_sensor.vent_air_quality_ok
            name: Qualità aria ok
          - entity: sensor.vent_weather_label
            name: Condizione meteo
