views:
  - title: Finestre
    path: ventilation_windows
    icon: mdi:window-open-variant
    type: sections
    max_columns: 2

    sections:
      - type: grid
        title: "Monitor finestre"
        cards:
          - type: glance
            columns: 2
            entities:
              - entity: sensor.windows_open_count
                name: Finestre aperte
              - entity: binary_sensor.windows_all_closed
                name: Casa chiusa
          - type: entities
            title: "Gruppi finestre"
            entities:
              - entity: group.windows_zona_giorno
                name: Zona giorno
              - entity: group.windows_zona_notte
                name: Zona notte
              - entity: group.windows_bagni
                name: Bagni
