views:
  - title: "Clima / VMC / Finestre"
    path: ventilation
    icon: mdi:home-thermometer
    type: sections
    max_columns: 3

    sections:
      - type: grid
        title: "Stato generale"
        cards:
          - type: glance
            columns: 3
            entities:
              - entity: sensor.clima_priority
                name: Clima Priority
              - entity: sensor.clima_reason
                name: Clima Reason
              - entity: binary_sensor.vmc_failsafe_sensors_bad
                name: Failsafe

          - type: entities
            show_header_toggle: false
            entities:
              - entity: sensor.vmc_vel_target
                name: Velocità target
              - entity: sensor.vmc_vel_index
                name: Indice velocità
              - entity: sensor.vmc_freecooling_status
                name: Free-cooling status

      - type: grid
        title: "Setpoint e comandi"
        cards:
          - type: entities
            title: "Soglie operative"
            show_header_toggle: false
            entities:
              - entity: input_number.vmc_bagno_on
                name: UR bagno ON
              - entity: input_number.vmc_bagno_off
                name: UR bagno OFF
              - entity: input_number.vmc_anti_secco_ur_min
                name: UR minima anti-secco
              - entity: input_number.vmc_fc_ph_tin_on
                name: FC PH — T_in ON
              - entity: input_number.vmc_fc_macchina_tout_min
                name: FC macchina — T_out min
              - entity: input_number.vmc_freecooling_delta
                name: ΔT free-cooling
              - entity: input_number.vmc_freecooling_delta_ah
                name: ΔAH free-cooling

          - type: entities
            title: "Controllo manuale"
            show_header_toggle: false
            entities:
              - entity: input_boolean.vmc_manual
                name: Manuale attivo
              - entity: input_select.vmc_manual_speed
                name: Velocità manuale
              - entity: timer.vmc_manual_timeout
                name: Timeout manuale

      - type: grid
        title: "KPI principali"
        cards:
          - type: entities
            entities:
              - entity: sensor.ur_in_min
                name: UR minima interna
              - entity: sensor.delta_ah_in_out
                name: ΔAH interno-esterno
              - entity: binary_sensor.clima_open_windows_recommended
                name: Consiglio apri finestre
              - entity: binary_sensor.vmc_override_ac_dry
                name: Override AC notte

      - type: grid
        title: "Grafici 24h / 7gg"
        cards:
          - type: history-graph
            title: "Velocità e UR bagno (24h)"
            hours_to_show: 24
            refresh_interval: 60
            entities:
              - entity: sensor.vmc_vel_index
                name: Velocità VMC
              - entity: sensor.ur_in_bagno
                name: UR bagno
              - entity: sensor.ur_out
                name: UR esterna

          - type: history-graph
            title: "Free-cooling (24h)"
            hours_to_show: 24
            refresh_interval: 60
            entities:
              - entity: sensor.vmc_freecooling_status
                name: Stato freecooling
              - entity: timer.vmc_freecooling_max_run
                name: Timer max-run
              - entity: timer.vmc_freecooling_cooldown
                name: Cooldown

          - type: statistics-graph
            title: "Velocità media (7 giorni)"
            days_to_show: 7
            period: day
            stat_types:
              - mean
            entities:
              - entity: sensor.vmc_vel_index
                name: Indice velocità

      - type: grid
        title: "Runtime e cicli"
        cards:
          - type: entities
            show_header_toggle: false
            entities:
              - entity: timer.vmc_anti_secco_lock
                name: Lock anti-secco
              - entity: timer.vmc_boost_lock
                name: Lock boost
              - entity: timer.vmc_freecooling_max_run
                name: Max-run freecooling
              - entity: timer.vmc_freecooling_cooldown
                name: Cooldown freecooling

      - type: grid
        title: "Debug"
        cards:
          - type: entities
            show_header_toggle: false
            collapsible: true
            entities:
              - entity: binary_sensor.clima_open_windows_recommended
                name: Clima — Apri finestre
              - entity: binary_sensor.vent_condizioni_meteo_ok
                name: Condizioni meteo OK
              - entity: binary_sensor.vent_condizioni_termiche_ok
                name: Condizioni termiche OK
              - entity: binary_sensor.vmc_bagno_boost
                name: Bagno / Boost
              - entity: binary_sensor.vmc_free_cooling_ph
                name: Free-cooling PH
              - entity: binary_sensor.vmc_free_cooling_machine
                name: Free-cooling macchina
              - entity: binary_sensor.vmc_anti_secco
                name: Anti-secco
              - entity: sensor.vmc_priority
                name: Priorità
              - entity: sensor.vmc_reason
                name: Reason
