views:
  - title: "1 · Ventilazione"
    path: vent
    icon: mdi:window-open-variant
    type: sections
    max_columns: 3

    sections:
      - type: grid
        title: "Stato generale"
        cards:
          - type: glance
            columns: 4
            entities:
              - entity: binary_sensor.vent_recommend_open
                name: Apri
                icon: mdi:window-open
              - entity: binary_sensor.vent_recommend_close
                name: Chiudi
                icon: mdi:window-closed-variant
              - entity: binary_sensor.vent_flag_estate
                name: Estate
                icon: mdi:white-balance-sunny
              - entity: binary_sensor.vent_night_flush_now
                name: Night flush
                icon: mdi:weather-night

          - type: entities
            title: "Messaggi"
            show_header_toggle: false
            entities:
              - entity: input_text.vent_messaggio_consiglio
                name: Consiglio attuale

      - type: grid
        title: "Setpoint e comandi"
        cards:
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_boolean.vent_override_estate
                name: Override stagione estiva
              - entity: input_boolean.vent_notifiche_attive
                name: Notifiche consigli
              - type: divider
              - entity: input_datetime.vent_night_flush_start
                name: Night flush start
              - entity: input_datetime.vent_night_flush_end
                name: Night flush end
              - type: divider
              - entity: input_number.vent_deltat_min
                name: ΔT minimo per APRI
              - entity: input_number.vent_deltaah_min
                name: ΔAH minimo per APRI
              - entity: input_number.vent_vento_max
                name: Vento massimo
              - entity: input_number.vent_pm25_max
                name: PM2.5 massimo

          - type: entities
            title: "Mappatura finestre"
            show_header_toggle: false
            entities:
              - entity: input_boolean.vent_finestra_giorno1_aperta
                name: Giorno 1 aperta
              - entity: input_boolean.vent_finestra_giorno2_aperta
                name: Giorno 2 aperta
              - entity: input_boolean.vent_portoncino_ingresso_aperto
                name: Portoncino ingresso
              - entity: input_boolean.vent_foro_cappa_aperto
                name: Foro cappa
              - entity: input_boolean.vent_finestra_notte1_aperta
                name: Notte 1 aperta
              - entity: input_boolean.vent_finestra_notte2_aperta
                name: Notte 2 aperta
              - entity: input_boolean.vent_finestra_notte3_aperta
                name: Notte 3 aperta
              - entity: input_boolean.vent_finestra_bagno_aperta
                name: Bagno aperta

      - type: grid
        title: "KPI principali"
        cards:
          - type: entities
            entities:
              - entity: sensor.t_out
                name: T esterna
              - entity: sensor.t_in_media
                name: T interna media
              - entity: sensor.delta_t_in_out
                name: ΔT in−out
              - type: divider
              - entity: sensor.ah_out
                name: AH esterna
              - entity: sensor.ah_in
                name: AH interna
              - entity: sensor.delta_ah_in_out
                name: ΔAH in−out
              - type: divider
              - entity: sensor.vent_meteo_vento
                name: Vento
              - entity: binary_sensor.vent_pioggia
                name: Pioggia
              - entity: binary_sensor.vent_air_quality_ok
                name: Qualità aria OK
              - entity: sensor.vent_meteo_pm25
                name: PM2.5

      - type: grid
        title: "Grafici 24h / 7gg"
        cards:
          - type: history-graph
            title: "Temperature 24h"
            hours_to_show: 24
            entities:
              - entity: sensor.t_out
                name: T out
              - entity: sensor.t_in_media
                name: T in media

          - type: history-graph
            title: "Umidità assoluta 24h"
            hours_to_show: 24
            entities:
              - entity: sensor.ah_out
                name: AH out
              - entity: sensor.ah_in
                name: AH in

          - type: statistics-graph
            title: "Trend 7 giorni"
            days_to_show: 7
            stat_types:
              - mean
              - min
              - max
            chart_type: line
            entities:
              - entity: sensor.t_out
                name: T out
              - entity: sensor.t_in_media
                name: T in media
              - entity: sensor.ah_out
                name: AH out
              - entity: sensor.ah_in
                name: AH in

      - type: grid
        title: "Runtime e finestre"
        cards:
          - type: entities
            show_header_toggle: false
            entities:
              - entity: sensor.vent_finestre_aperte
                name: Finestre aperte
              - entity: sensor.vent_finestre_state
                name: Dettaglio finestre
              - type: section
                label: Ultimi cambi manuali
              - entity: input_datetime.vent_last_change_giorno1
                name: Giorno 1
              - entity: input_datetime.vent_last_change_giorno2
                name: Giorno 2
              - entity: input_datetime.vent_last_change_portoncino
                name: Portoncino
              - entity: input_datetime.vent_last_change_foro_cappa
                name: Foro cappa
              - entity: input_datetime.vent_last_change_notte1
                name: Notte 1
              - entity: input_datetime.vent_last_change_notte2
                name: Notte 2
              - entity: input_datetime.vent_last_change_notte3
                name: Notte 3
              - entity: input_datetime.vent_last_change_bagno
                name: Bagno

      - type: grid
        title: "Debug"
        cards:
          - type: entities
            show_header_toggle: false
            collapsible: true
            entities:
              - entity: sensor.t_out
                name: T out (canonico)
              - entity: sensor.t_in_media
                name: T in media (canonico)
              - entity: sensor.ah_out
                name: AH out (canonico)
              - entity: sensor.ah_in
                name: AH in (canonico)
              - entity: sensor.vent_meteo_temp
                name: REST — T out
              - entity: sensor.vent_meteo_rh
                name: REST — UR out
              - entity: sensor.vent_meteo_vento
                name: REST — vento
              - entity: sensor.vent_meteo_precip
                name: REST — pioggia
