views:
  - title: Ventilazione
    path: ventilation
    icon: mdi:air-filter
    type: sections
    max_columns: 3

    sections:
      - type: grid
        title: "Stato generale VMC"
        cards:
          - type: glance
            columns: 3
            entities:
              - entity: sensor.vmc_priority
                name: VMC Priority
              - entity: sensor.vmc_reason
                name: VMC Reason
              - entity: sensor.vmc_freecooling_status
                name: Freecooling
          - type: entities
            title: "Velocità e controlli"
            show_header_toggle: false
            entities:
              - entity: sensor.vmc_vel_target
                name: Velocità target
              - entity: sensor.vmc_vel_index
                name: Indice velocità
              - entity: input_boolean.vmc_manual
                name: Manuale attivo
              - entity: input_select.vmc_manual_speed
                name: Velocità manuale
              - entity: timer.vmc_manual_timeout
                name: Timeout manuale
              - entity: binary_sensor.vmc_failsafe_sensors_bad
                name: Failsafe sensori

      - type: grid
        title: "KPI + Consigli"
        cards:
          - type: entities
            title: "Freecooling / ΔT / ΔAH"
            show_header_toggle: false
            entities:
              - entity: sensor.delta_t_in_out
                name: ΔT interno-esterno
              - entity: sensor.delta_ah_in_out
                name: ΔAH interno-esterno
              - entity: input_number.vmc_freecooling_delta
                name: Soglia ΔT FC
              - entity: input_number.vmc_freecooling_delta_ah
                name: Soglia ΔAH FC
              - entity: binary_sensor.vent_condizioni_termiche_ok
                name: Condizioni termiche OK
              - entity: binary_sensor.vent_condizioni_meteo_ok
                name: Meteo OK
              - entity: binary_sensor.vent_recommend_open
                name: "Consiglio: apri finestre"
              - entity: binary_sensor.vent_recommend_close
                name: "Consiglio: chiudi finestre"
              - entity: sensor.ventilation_priority
                name: Priorità ventilazione
              - entity: sensor.ventilation_reason
                name: Reason ventilazione
          - type: entities
            title: "Stagionalità e meteo"
            show_header_toggle: false
            entities:
              - entity: binary_sensor.stagione_calda
                name: Stagione calda
              - entity: binary_sensor.stagione_fredda
                name: Stagione fredda
              - entity: sensor.vent_meteo_temp
                name: T esterna (open-meteo)
              - entity: sensor.vent_meteo_rh
                name: UR esterna (open-meteo)
              - entity: sensor.vent_meteo_vento
                name: Vento
              - entity: sensor.vent_meteo_precip
                name: Pioggia
              - entity: sensor.vent_meteo_pm25
                name: PM2.5
              - entity: binary_sensor.vent_weather_block
                name: Blocco meteo

      - type: grid
        title: "Finestre"
        cards:
          - type: entities
            title: "Stato finestre"
            show_header_toggle: false
            entities:
              - entity: sensor.vent_finestre_aperte
                name: Totale finestre aperte
              - entity: sensor.vent_finestre_state
                name: Dettaglio finestre aperte
              - entity: binary_sensor.clima_open_windows_recommended
                name: Apri finestre raccomandato
          - type: history-graph
            hours_to_show: 24
            entities:
              - entity: sensor.delta_t_in_out
              - entity: sensor.delta_ah_in_out
              - entity: sensor.vmc_freecooling_status
              - entity: binary_sensor.vent_recommend_open
            title: "Trend 24h ΔT/ΔAH"
          - type: history-graph
            hours_to_show: 48
            entities:
              - entity: sensor.ventilation_priority
              - entity: sensor.vmc_priority
              - entity: binary_sensor.vmc_failsafe_sensors_bad
            title: "Priorità ventilazione"
