###############################################################################
# 2_vmc_plancia.yaml — Plancia VMC (Passivhaus-oriented)
# Coerente con 0_sensors.yaml e 2_vmc.yaml — layout "Regole Plancia v2"
# Se servono modifiche ad altri file, NON inserirle qui.
###############################################################################

views:
  - title: "2 — VMC"
    type: sections
    max_columns: 3

    sections:

      # =====================================================
      # COLONNA 1 — STATO & COMANDI RAPIDI
      # =====================================================
      - type: grid
        cards:

          # -- Stato logico (chip/glance)
          - type: glance
            title: "Stato logico"
            show_state: true
            show_icon: true
            entities:
              - entity: sensor.vmc_priority
                name: "Priorità"
                icon: mdi:arrow-top-right-bold-outline
              - entity: sensor.vmc_reason
                name: "Motivo"
                icon: mdi:text
              - entity: sensor.vmc_last_event
                name: "Ultimo evento"
                icon: mdi:clock-outline
              - entity: binary_sensor.stagione_calda
                name: "Stagione calda"
              - entity: binary_sensor.stagione_fredda
                name: "Stagione fredda"

          # -- Comandi rapidi: velocità VMC (tap = ON diretto)
          - type: grid
            title: "Comandi velocità"
            columns: 2
            cards:
              - type: button
                name: "vel_0"
                icon: mdi:fan-off
                entity: switch.vmc_vel_0
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  target:
                    entity_id: switch.vmc_vel_0
              - type: button
                name: "vel_1"
                icon: mdi:fan-speed-1
                entity: switch.vmc_vel_1
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  target:
                    entity_id: switch.vmc_vel_1
              - type: button
                name: "vel_2"
                icon: mdi:fan-speed-2
                entity: switch.vmc_vel_2
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  target:
                    entity_id: switch.vmc_vel_2
              - type: button
                name: "vel_3 (Boost)"
                icon: mdi:fan-speed-3
                entity: switch.vmc_vel_3
                tap_action:
                  action: call-service
                  service: switch.turn_on
                  target:
                    entity_id: switch.vmc_vel_3

          # -- Stato attuatori
          - type: glance
            title: "Attuatori"
            entities:
              - entity: switch.vmc_vel_0
                name: vel_0
              - entity: switch.vmc_vel_1
                name: vel_1
              - entity: switch.vmc_vel_2
                name: vel_2
              - entity: switch.vmc_vel_3
                name: vel_3
              - entity: switch.ac_giorno
                name: AC giorno
              - entity: switch.ac_notte
                name: AC notte

          # -- Spiegazione umana (Come decide)
          - type: markdown
            title: "Come decide"
            content: |
              **Arbitraggio top‑down (prime vere vincono):**
              - **P0 — Failsafe** → `vel_0` (sensori KO).
              - **Override — AC notte = DRY** → `vel_0` (evita aria umida durante deumidifica).
              - **P1 — Bagno/Boost** → `vel_3` (UR bagno ≥ 75% o ΔUR ≥ 10%; stop a UR ≤ 65% e ΔUR ≤ 5%).
              - **P2 — Free‑cooling** → `vel_2`:
                - *Passivhaus*: `T_in > 24°C`, `T_out < T_in`, `AH_out < AH_in` (lock 15').
                - *Macchina*: `T_in > 24°C`, `20°C < T_out < T_in` (lock 15').
                - Se entrambe vere → prevale **Passivhaus**.
              - **P3 — Anti‑secco (inverno, notte)** → `vel_0` con duty (5' ON/30').
              - **P4 — Baseline** → `vel_1`.

      # =====================================================
      # COLONNA 2 — KPI PRINCIPALI (tile con grafico)
      # =====================================================
      - type: grid
        cards:
          # --- Temperature base (Rosso esterno, Giallo giorno, Blu notte, Verde bagno)
          - type: tile
            entity: sensor.t_out
            name: "T Esterna"
            icon: mdi:thermometer
            color: red
            features:
              - type: graph
                graph: line
          - type: tile
            entity: sensor.t_in_giorno
            name: "T Giorno"
            icon: mdi:thermometer
            color: amber
            features:
              - type: graph
                graph: line
          - type: tile
            entity: sensor.t_in_notte1
            name: "T Notte"
            icon: mdi:thermometer
            color: blue
            features:
              - type: graph
                graph: line
          - type: tile
            entity: sensor.t_in_bagno
            name: "T Bagno"
            icon: mdi:thermometer
            color: green
            features:
              - type: graph
                graph: line

          # --- Umidità base
          - type: tile
            entity: sensor.ur_out
            name: "UR Esterna"
            icon: mdi:water-percent
            color: red
            features:
              - type: graph
                graph: line
          - type: tile
            entity: sensor.ur_in_giorno
            name: "UR Giorno"
            icon: mdi:water-percent
            color: amber
            features:
              - type: graph
                graph: line
          - type: tile
            entity: sensor.ur_in_notte1
            name: "UR Notte"
            icon: mdi:water-percent
            color: blue
            features:
              - type: graph
                graph: line
          - type: tile
            entity: sensor.ur_in_bagno
            name: "UR Bagno"
            icon: mdi:water-percent
            color: green
            features:
              - type: graph
                graph: line

          # --- Derivate/medie (neutri)
          - type: tile
            entity: sensor.t_in_media
            name: "T interna media"
            icon: mdi:thermometer
            features:
              - type: graph
                graph: line
          - type: tile
            entity: sensor.ur_in_media
            name: "UR interna media"
            icon: mdi:water-percent
            features:
              - type: graph
                graph: line
          - type: tile
            entity: sensor.ur_in_min
            name: "UR minima (int)"
            icon: mdi:water-percent
            features:
              - type: graph
                graph: line
          - type: tile
            entity: sensor.dewpoint_in
            name: "Dew point (int)"
            icon: mdi:thermometer-alert
            features:
              - type: graph
                graph: line
          - type: tile
            entity: sensor.ah_in
            name: "AH interna (g/m³)"
            icon: mdi:water
            features:
              - type: graph
                graph: line
          - type: tile
            entity: sensor.ah_out
            name: "AH esterna (g/m³)"
            icon: mdi:water-outline
            features:
              - type: graph
                graph: line
          - type: tile
            entity: sensor.delta_t_in_out
            name: "ΔT (in−out)"
            icon: mdi:delta
            features:
              - type: graph
                graph: line
          - type: tile
            entity: sensor.delta_ah_in_out
            name: "ΔAH (in−out)"
            icon: mdi:delta
            features:
              - type: graph
                graph: line

      # =====================================================
      # COLONNA 3 — TREND & LOCK / DIAGNOSTICA
      # =====================================================
      - type: grid
        cards:

          # Confronti compatti (mini-graph-card)
          - type: custom:mini-graph-card
            name: "T interna vs esterna (24h)"
            hours_to_show: 24
            line_width: 2
            points_per_hour: 6
            show:
              fill: false
              points: false
              legend: true
            entities:
              - entity: sensor.t_in_media
                name: T_in
              - entity: sensor.t_out
                name: T_out

          - type: custom:mini-graph-card
            name: "AH in vs out (24h)"
            hours_to_show: 24
            line_width: 2
            points_per_hour: 6
            show:
              fill: false
              points: false
              legend: true
            entities:
              - entity: sensor.ah_in
                name: AH_in
              - entity: sensor.ah_out
                name: AH_out

          # History-graph: umidità & dew point (24h)
          - type: history-graph
            title: "UR & Dewpoint — 24h"
            hours_to_show: 24
            refresh_interval: 0
            entities:
              - sensor.ur_in_media
              - sensor.ur_out
              - sensor.dewpoint_in

          # Statistics-graph: medie settimanali (7gg)
          - type: statistics-graph
            title: "Statistiche 7gg"
            days_to_show: 7
            chart_type: line
            period: day
            entities:
              - sensor.t_in_media
              - sensor.ur_in_media

          # Debug sensori base (per scovare unknown)
          - type: entities
            title: "Debug sensori base"
            show_header_toggle: false
            entities:
              - sensor.t_in_giorno
              - sensor.t_in_notte1
              - sensor.t_in_bagno
              - sensor.t_out
              - sensor.ur_in_giorno
              - sensor.ur_in_notte1
              - sensor.ur_in_bagno
              - sensor.ur_out

          # Debug derivate/diagnostica
          - type: entities
            title: "Debug derivate e diagnostica"
            show_header_toggle: false
            entities:
              - sensor.t_in_media
              - sensor.ur_in_media
              - sensor.ur_in_min
              - sensor.ah_in
              - sensor.ah_out
              - sensor.dewpoint_in
              - sensor.delta_t_in_out
              - sensor.delta_ah_in_out
              - sensor.vmc_priority
              - sensor.vmc_reason
              - sensor.vmc_last_event
              - binary_sensor.stagione_calda
              - binary_sensor.stagione_fredda
