views:
  - title: "Aria Condizionata"
    path: ac
    icon: mdi:air-conditioner
    type: sections
    max_columns: 3

    sections:
      # ===========================
      # SEZIONE 1 — STATO & COMANDI
      # ===========================
      - type: grid
        cards:
          - type: entities
            title: "AC — Stato generale"
            show_header_toggle: false
            entities:
              - entity: switch.ac_giorno
                name: "AC Giorno"
              - entity: switch.ac_notte
                name: "AC Notte"
              - entity: sensor.ac_priority
                name: "Priorità attuale"
              - entity: sensor.ac_reason
                name: "Motivo / modalità"

          - type: entities
            title: "Modalità & manuale"
            show_header_toggle: false
            entities:
              - entity: input_boolean.ac_manual
                name: "Manuale attivo"
              - entity: input_select.ac_manual_mode
                name: "Modalità manuale"
              - entity: timer.ac_manual_timeout
                name: "Timeout manuale"
              - entity: input_boolean.ac_block_vmc
                name: "Block da VMC"
              - entity: timer.ac_block_vmc_timeout
                name: "Timeout block VMC"

      # ===========================
      # SEZIONE 2 — SETPOINT & SOGLIE
      # ===========================
      - type: grid
        cards:
          - type: entities
            title: "Setpoint COOL / DRY"
            show_header_toggle: false
            entities:
              - entity: input_number.ac_cool_setpoint
                name: "Setpoint COOL (°C)"
              - entity: input_number.ac_dry_ur_on
                name: "UR ON DRY (%)"
              - entity: input_number.ac_dry_ur_off
                name: "UR OFF DRY (%)"

          - type: entities
            title: "Anti-ciclo & runtime"
            show_header_toggle: false
            entities:
              - entity: input_number.ac_min_on_minutes
                name: "AC — Min ON (min)"
              - entity: input_number.ac_min_off_minutes
                name: "AC — Min OFF (min)"
              - entity: input_number.ac_min_on
                name: "Legacy Min ON (storico)"
                visible: false
              - entity: input_number.ac_min_off
                name: "Legacy Min OFF (storico)"
                visible: false

      # ===========================
      # SEZIONE 3 — FINESTRE & BLOCCHI
      # ===========================
      - type: grid
        cards:
          - type: entities
            title: "Blocchi & failsafe"
            show_header_toggle: false
            entities:
              - entity: binary_sensor.ac_failsafe_sensors_bad
                name: "Failsafe sensori"
              - entity: binary_sensor.ac_block_by_vmc
                name: "Block VMC attivo"
              - entity: binary_sensor.ac_lock_min_on_ok
                name: "Lock min ON OK"
              - entity: binary_sensor.ac_lock_min_off_ok
                name: "Lock min OFF OK"
              - entity: binary_sensor.stagione_calda
                name: "Stagione calda"

          - type: entities
            title: "Ultimi comandi"
            show_header_toggle: false
            entities:
              - entity: sensor.ac_giorno_ultimo_on
                name: "AC Giorno — ultimo ON"
              - entity: sensor.ac_giorno_ultimo_off
                name: "AC Giorno — ultimo OFF"
              - entity: sensor.ac_notte_ultimo_on
                name: "AC Notte — ultimo ON"
              - entity: sensor.ac_notte_ultimo_off
                name: "AC Notte — ultimo OFF"

      # ===========================
      # SEZIONE 4 — TREND TERMICO/IGROMETRICO
      # ===========================
      - type: grid
        cards:
          - type: history-graph
            title: "Temperature interne/esterna (24h)"
            hours_to_show: 24
            refresh_interval: 60
            entities:
              - entity: sensor.t_in_media
                name: "T interna media"
              - entity: sensor.t_out
                name: "T esterna"

          - type: history-graph
            title: "Umidità interna/esterna (24h)"
            hours_to_show: 24
            refresh_interval: 60
            entities:
              - entity: sensor.ur_in_media
                name: "UR interna media"
              - entity: sensor.ur_out
                name: "UR esterna"

      # ===========================
      # SEZIONE 5 — RUNTIME & CICLI
      # ===========================
      - type: grid
        cards:
          - type: entities
            title: "Runtime oggi"
            show_header_toggle: false
            entities:
              - entity: sensor.ac_giorno_tempo_on_oggi
                name: "AC Giorno — tempo ON oggi (h)"
              - entity: sensor.ac_giorno_cicli_on_oggi
                name: "AC Giorno — cicli ON oggi"
              - entity: sensor.ac_notte_tempo_on_oggi
                name: "AC Notte — tempo ON oggi (h)"
              - entity: sensor.ac_notte_cicli_on_oggi
                name: "AC Notte — cicli ON oggi"

          - type: history-graph
            title: "Trend ON/OFF AC (24h)"
            hours_to_show: 24
            refresh_interval: 60
            entities:
              - entity: switch.ac_giorno
                name: "AC Giorno"
              - entity: switch.ac_notte
                name: "AC Notte"

      # ===========================
      # SEZIONE 6 — DEBUG CONTROLLER
      # ===========================
      - type: grid
        cards:
          - type: entities
            title: "DEBUG — Controller AC"
            show_header_toggle: false
            entities:
              - entity: sensor.ac_priority
                name: "Priorità"
              - entity: sensor.ac_reason
                name: "Reason / mode / target"
              - entity: input_boolean.ac_manual
                name: "Manuale attivo"
              - entity: input_boolean.ac_block_vmc
                name: "Block da VMC"
              - entity: binary_sensor.ac_failsafe_sensors_bad
                name: "Failsafe sensori"
              - entity: binary_sensor.ac_block_by_vmc
                name: "Block by VMC"
