title: "6 Energia — Core & Bilanci"
views:
  - title: "Energia — Monitor & Bilanci"
    path: energia-monitor
    icon: mdi:solar-power
    type: sections
    max_columns: 3
    sections:

      # ==================== 1) STATO & COMANDI RAPIDI ==========================
      - type: grid
        title: "Stato & Comandi"
        cards:
          - type: glance
            title: "Stato generale"
            show_name: true
            show_state: true
            entities:
              - entity: binary_sensor.grid_connected
                name: "Connessione rete"
                icon: mdi:transmission-tower
              - entity: binary_sensor.pv_active
                name: "PV attivo"
                icon: mdi:solar-panel
              - entity: binary_sensor.exporting
                name: "In immissione"
                icon: mdi:export
              - entity: binary_sensor.importing
                name: "In prelievo"
                icon: mdi:import
              - entity: binary_sensor.surplus_active
                name: "Surplus PV"
                icon: mdi:battery-arrow-up

      # ==================== 2) KPI PRINCIPALI OGGI ============================
      - type: grid
        title: "KPI oggi"
        cards:
          - type: grid
            columns: 2
            square: false
            cards:
              - type: tile
                entity: sensor.pv_today_kwh
                name: "FV — kWh oggi"
                icon: mdi:solar-panel
              - type: tile
                entity: sensor.grid_import_today_kwh
                name: "Rete — kWh import"
                icon: mdi:transmission-tower
              - type: tile
                entity: sensor.grid_export_today_kwh
                name: "Rete — kWh export"
                icon: mdi:transmission-tower-export
              - type: tile
                entity: sensor.home_today_kwh
                name: "Casa — kWh totali"
                icon: mdi:home-lightning-bolt

      # ==================== 3) ANDAMENTO GIORNALIERO (24h) ====================
      - type: grid
        title: "Andamento 24h"
        cards:
          - type: custom:mini-graph-card
            name: "Produzione FV / Consumo / Rete"
            hours_to_show: 24
            points_per_hour: 4
            show:
              fill: false
              legend: true
              labels: true
              state: true
            entities:
              - entity: sensor.pv_power
                name: "FV [W]"
                color: '#fdd835'
              - entity: sensor.grid_power
                name: "Rete [W]"
                color: '#9e9e9e'
              - entity: sensor.home_power
                name: "Casa [W]"
                color: '#42a5f5'
          - type: custom:mini-graph-card
            name: "Bilancio istantaneo (FV - Casa)"
            hours_to_show: 24
            points_per_hour: 4
            show:
              fill: false
              legend: true
              labels: true
              state: true
            entities:
              - entity: sensor.energy_balance_now
                name: "ΔEnergia"
                color: '#ab47bc'
                y_axis: secondary

      # ==================== 4) TREND SETTIMANALE / MENSILE ====================
      - type: grid
        title: "Trend 7gg / 30gg"
        cards:
          - type: statistics-graph
            title: "Bilancio energetico 7 giorni"
            days_to_show: 7
            period: day
            chart_type: bar
            entities:
              - entity: sensor.pv_today_kwh
                name: "FV"
              - entity: sensor.grid_import_today_kwh
                name: "Rete Import"
              - entity: sensor.grid_export_today_kwh
                name: "Rete Export"
              - entity: sensor.home_today_kwh
                name: "Casa"
          - type: statistics-graph
            title: "Bilancio energetico 30 giorni"
            days_to_show: 30
            period: day
            chart_type: line
            entities:
              - entity: sensor.pv_today_kwh
                name: "FV"
              - entity: sensor.home_today_kwh
                name: "Casa"
              - entity: sensor.grid_import_today_kwh
                name: "Import"
              - entity: sensor.grid_export_today_kwh
                name: "Export"

      # ==================== 5) SOGLIE & LOCK (Surplus / PV) ===================
      - type: grid
        title: "Soglie & Lock"
        cards:
          - type: entities
            title: "Parametri energia"
            show_header_toggle: false
            entities:
              - entity: input_number.surplus_min_power
                name: "Soglia surplus (W)"
              - entity: input_number.surplus_lock_time
                name: "Tempo lock (min)"
              - entity: input_boolean.surplus_enable
                name: "Surplus attivo"
              - entity: input_boolean.energy_debug
                name: "Debug energia"

      # ==================== 6) SPIEGAZIONE LOGICA =============================
      - type: markdown
        title: "Come decide"
        content: |
          ### ⚙️ Logica energetica
          - La plancia mostra produzione, consumi e bilanci dell’abitazione.
          - La produzione FV (sensor.pv_today_kwh) rappresenta l’energia generata.
          - Il consumo casa è la somma delle utenze dirette.
          - L’import/export rete derivano dai sensori di pinza o SolarEdge.
          - Il **bilancio istantaneo** (ΔEnergia) è FV − Casa:
            - positivo → surplus in immissione  
            - negativo → prelievo da rete  
          - Se `binary_sensor.surplus_active` è ON, sono attivi i carichi PV-driven.
          - Soglie regolabili in “Parametri energia”.

      # ==================== 7) DEBUG & SENSORI GREZZI ========================
      - type: grid
        title: "Debug sensori grezzi"
        cards:
          - type: entities
            title: "Sensori base"
            show_header_toggle: false
            entities:
              - sensor.pv_power
              - sensor.grid_power
              - sensor.home_power
              - sensor.pv_today_kwh
              - sensor.grid_import_today_kwh
              - sensor.grid_export_today_kwh
              - sensor.home_today_kwh
