views:
  - title: "Debug Sistema"
    path: debug-sistema
    icon: mdi:tools
    type: sections
    max_columns: 3

    sections:
      - type: grid
        title: "Stato generale"
        cards:
          - type: glance
            title: "VMC"
            show_name: true
            entities:
              - entity: sensor.vmc_priority
                name: Priorità
              - entity: sensor.vmc_reason
                name: Reason
              - entity: binary_sensor.vmc_failsafe_sensors_bad
                name: Failsafe
              - entity: sensor.vmc_vel_target
                name: Velocità

          - type: glance
            title: "AC"
            entities:
              - entity: sensor.ac_priority
                name: Priorità
              - entity: sensor.ac_reason
                name: Reason
              - entity: binary_sensor.ac_block_by_vmc
                name: Block VMC
              - entity: binary_sensor.ac_lock_min_on_ok
                name: Lock ON

          - type: glance
            title: "Heating"
            entities:
              - entity: sensor.heating_priority
                name: Priorità
              - entity: sensor.heating_reason
                name: Reason
              - entity: binary_sensor.heating_window_comfort
                name: Finestra comfort
              - entity: switch.4_ch_interrutore_3
                name: Pompa

          - type: glance
            title: "Vent naturale"
            entities:
              - entity: binary_sensor.vent_recommend_open
                name: Apri
              - entity: binary_sensor.vent_recommend_close
                name: Chiudi
              - entity: binary_sensor.vent_flag_estate
                name: Estate
              - entity: binary_sensor.vent_night_flush_now
                name: Night flush

      - type: grid
        title: "Setpoint e comandi"
        cards:
          - type: entities
            title: "VMC"
            entities:
              - entity: input_boolean.vmc_manual
                name: Manuale attivo
              - entity: input_select.vmc_manual_speed
                name: Velocità manuale
              - entity: timer.vmc_manual_timeout
                name: Timeout manuale

          - type: entities
            title: "AC"
            entities:
              - entity: input_boolean.ac_manual
                name: Manuale attivo
              - entity: input_select.ac_manual_mode
                name: Modalità manuale
              - entity: timer.ac_manual_timeout
                name: Timeout manuale
              - entity: input_boolean.ac_block_vmc
                name: Block da VMC
              - entity: timer.ac_block_vmc_timeout
                name: Timeout block VMC

          - type: entities
            title: "Heating"
            entities:
              - entity: input_boolean.heating_manual_active
                name: Manuale attivo
              - entity: input_select.heating_manual_mode
                name: Modalità manuale
              - entity: timer.heating_manual_timeout
                name: Timeout manuale
              - entity: input_boolean.heating_force_on
                name: Forza ON
              - entity: input_boolean.heating_force_off
                name: Forza OFF

      - type: grid
        title: "KPI microclima"
        cards:
          - type: entities
            entities:
              - entity: sensor.t_in_giorno
                name: T Giorno
              - entity: sensor.t_in_notte1
                name: T Notte 1
              - entity: sensor.t_in_bagno
                name: T Bagno
              - entity: sensor.t_out
                name: T Esterna
              - entity: sensor.ur_in_media
                name: UR interna
              - entity: sensor.ur_in_bagno
                name: UR Bagno
              - entity: sensor.ur_out
                name: UR esterna
              - entity: sensor.ah_in
                name: AH interna
              - entity: sensor.ah_out
                name: AH esterna

      - type: grid
        title: "Grafici 24h"
        cards:
          - type: history-graph
            title: "Temperature"
            hours_to_show: 24
            entities:
              - sensor.t_in_giorno
              - sensor.t_in_notte1
              - sensor.t_in_bagno
              - sensor.t_out

          - type: history-graph
            title: "Umidità relativa"
            hours_to_show: 24
            entities:
              - sensor.ur_in_media
              - sensor.ur_in_bagno
              - sensor.ur_out

          - type: history-graph
            title: "Logiche VMC"
            hours_to_show: 24
            entities:
              - binary_sensor.vmc_bagno_boost
              - binary_sensor.vmc_free_cooling_ph
              - binary_sensor.vmc_free_cooling_machine
              - binary_sensor.vmc_anti_secco
              - sensor.vmc_vel_target

          - type: history-graph
            title: "AC e Heating"
            hours_to_show: 24
            entities:
              - switch.ac_giorno
              - switch.ac_notte
              - switch.4_ch_interrutore_3

      - type: grid
        title: "Debug"
        cards:
          - type: entities
            title: "Soglie principali"
            entities:
              - entity: input_number.vent_deltat_min
                name: ΔT Vent
              - entity: input_number.vent_deltaah_min
                name: ΔAH Vent
              - entity: input_number.vent_vento_max
                name: Vento max
              - entity: input_number.vmc_fc_ph_tin_on
                name: FC — T_in ON
              - entity: input_number.vmc_fc_macchina_tout_min
                name: FC — T_out >
              - entity: input_number.ac_cool_setpoint
                name: Setpoint COOL
              - entity: input_number.ac_dry_ur_on
                name: UR ON DRY
              - entity: input_number.temp_target_risc
                name: Heating target

          - type: entity-filter
            title: "Sensori non disponibili"
            show_empty: false
            state_filter:
              - "unknown"
              - "unavailable"
            card:
              type: entities
            entities:
              - sensor.t_in_giorno
              - sensor.t_in_notte1
              - sensor.t_in_bagno
              - sensor.t_out
              - sensor.ur_in_media
              - sensor.ur_in_bagno
              - sensor.ur_out
              - sensor.ah_in
              - sensor.ah_out
              - binary_sensor.vmc_failsafe_sensors_bad
              - binary_sensor.vmc_bagno_boost
              - binary_sensor.vmc_free_cooling_ph
              - binary_sensor.vmc_free_cooling_machine
              - binary_sensor.vmc_anti_secco
              - binary_sensor.ac_block_by_vmc
              - binary_sensor.heating_window_comfort
