views:
  - title: "Test"
    path: test
    type: sections
    max_columns: 2
    sections:
      - type: grid
        title: "Stato"
        cards:
          - type: markdown
            content: "Dashboard Test attiva."

      - type: grid
        title: "Grafici"
        cards:
          - type: history-graph
            title: "Temperatura zona giorno"
            hours_to_show: 6
            refresh_interval: 0
            entities:
              - entity: sensor.t_in_giorno
