panel: true
views:
  - title: "VMC v2"
    icon: mdi:fan-auto
    path: vmc-v2
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              ## Stato aria & meteo
          - type: entities
            title: "Aria indoor/outdoor"
            show_header_toggle: false
            entities:
              - entity: sensor.t_in_med
                name: "T interna media"
              - entity: sensor.ur_in_media
                name: "UR interna media"
              - entity: sensor.t_out
                name: "T esterna"
              - entity: sensor.ur_out
                name: "UR esterna"
          - type: weather-forecast
            entity: weather.home
            show_forecast: true

          - type: markdown
            content: |
              ## Stato VMC
          - type: entities
            show_header_toggle: false
            entities:
              - entity: sensor.ventilation_priority
                name: "Priorità ventilazione"
              - entity: sensor.ventilation_reason
                name: "Motivo ventilazione"
              - entity: binary_sensor.vmc_sensors_ok
                name: "Sensori VMC ok"
              - entity: binary_sensor.vent_condizioni_meteo_ok
                name: "Condizioni meteo ok"
              # TODO: binary_sensor.clima_open_windows mancante nella MAP
              - entity: binary_sensor.clima_ac_from_vmc_request
                name: "AC richiesta dal clima"

          - type: markdown
            content: |
              ## Modalità & controlli manuali
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_select.vmc_mode
                name: "Modalità VMC"
              - entity: input_boolean.vmc_manual
                name: "Abilita manuale"
              - entity: input_select.vmc_manual_speed
                name: "Velocità manuale"
              - entity: input_boolean.vmc_boost_bagno
                name: "Boost bagno"

          - type: markdown
            content: |
              ## KPI aria & grafico 24h
          - type: entities
            show_header_toggle: false
            entities:
              - entity: sensor.t_in_med
                name: "T interna media"
              - entity: sensor.delta_t_in_out
                name: "ΔT in–out"
              - entity: sensor.delta_ah_in_out
                name: "ΔAH in–out"
          - type: sensor
            name: "T interna media — 24h"
            entity: sensor.t_in_med
            graph: line
            hours_to_show: 24
            detail: 1

          - type: markdown
            content: |
              ## Zone termiche
          - type: entities
            show_header_toggle: false
            entities:
              - type: section
                label: "Bagno"
              - entity: sensor.t_in_bagno
                name: "T bagno"
              - entity: sensor.ur_in_bagno
                name: "UR bagno"
              - type: section
                label: "Zona giorno"
              - entity: sensor.t_in_giorno
                name: "T zona giorno"
              - entity: sensor.ur_in_giorno
                name: "UR zona giorno"
              - type: section
                label: "Zona notte"
              - entity: sensor.t_in_notte1
                name: "T notte 1"
              - entity: sensor.t_in_notte2
                name: "T notte 2"
              - entity: sensor.ur_in_notte1
                name: "UR notte 1"
              - entity: sensor.ur_in_notte2
                name: "UR notte 2"

          - type: markdown
            content: |
              ## Velocità reali VMC
          - type: entities
            show_header_toggle: false
            entities:
              - entity: sensor.vmc_vel_target
                name: "Velocità target"
              - entity: sensor.vmc_vel_index
                name: "Indice velocità"
              - entity: switch.vmc_vel_0
                name: "vel 0"
              - entity: switch.vmc_vel_1
                name: "vel 1"
              - entity: switch.vmc_vel_2
                name: "vel 2"
              - entity: switch.vmc_vel_3
                name: "vel 3"
          - type: history-graph
            title: "Storico velocità target (24h)"
            hours_to_show: 24
            entities:
              - entity: sensor.vmc_vel_target

          - type: markdown
            content: |
              ## Freecooling
          - type: entities
            show_header_toggle: false
            entities:
              - entity: binary_sensor.vmc_freecooling_candidate
                name: "Freecooling candidabile"
              - entity: binary_sensor.vmc_freecooling_active
                name: "Freecooling attivo"
              - entity: sensor.vmc_freecooling_status
                name: "Stato freecooling"
              - entity: sensor.t_in_med
                name: "T interna media"
              - entity: sensor.t_out
                name: "T esterna"

          - type: markdown
            content: |
              ## Trigger principali (bagno, finestre, AC)
          - type: entities
            show_header_toggle: false
            entities:
              - entity: sensor.ur_in_bagno
                name: "UR bagno"
              - entity: input_number.vmc_bagno_on
                name: "Soglia boost ON"
              - entity: input_number.vmc_bagno_off
                name: "Soglia boost OFF"
              - entity: binary_sensor.clima_ac_from_vmc_request
                name: "AC richiesta dal clima"
          - type: markdown
            content: |
              ### Trigger VMC
              - Boost bagno attivo se `ur_bagno` > soglia
              - Freecooling candidabile se: T_in > 24°C, T_out < T_in, T_out > 20°C
              - AC richiesta dal clima: {{ states('binary_sensor.clima_ac_from_vmc_request') }}

          - type: markdown
            content: |
              ## Spiegazione stato attuale
          - type: entities
            show_header_toggle: false
            entities:
              - entity: sensor.ventilation_reason
                name: "Motivo ventilazione"
              - entity: sensor.ventilation_priority
                name: "Priorità ventilazione"
              - entity: binary_sensor.clima_ac_from_vmc_request
                name: "AC richiesta dal clima"
