title: "1 — Ventilazione"
icon: mdi:fan
views:
  - title: "VMC"
    icon: mdi:fan-auto
    path: vmc
    cards:
      - type: entities
        title: "1 — Stato generale VMC"
        show_header_toggle: false
        entities:
          - entity: sensor.ventilation_priority
            name: Priorità corrente
          - entity: sensor.ventilation_reason
            name: Motivo
          - entity: sensor.vmc_freecooling_status
            name: Stato freecooling
          - entity: binary_sensor.vmc_sensors_ok
            name: Sensori critici ok

      - type: entities
        title: "2 — KPI ambiente"
        show_header_toggle: false
        entities:
          - entity: sensor.t_in_media
            name: T interna media
          - entity: sensor.ur_in_media
            name: UR interna media
          - entity: sensor.delta_t_in_out
            name: ΔT (interno-esterno)
          - entity: sensor.delta_ah_in_out
            name: ΔAH (interno-esterno)

      - type: entities
        title: "3 — Controllo manuale VMC"
        show_header_toggle: false
        entities:
          - entity: input_select.vmc_mode
            name: Modalità VMC
          - entity: input_boolean.vmc_manual
            name: Manuale abilitato
          - entity: input_select.vmc_manual_speed
            name: Velocità manuale
          - entity: input_boolean.vmc_boost_bagno
            name: Boost bagno manuale
          - entity: input_boolean.vent_override_estate
            name: Forza estate

      - type: entities
        title: "4 — Velocità reali e target"
        show_header_toggle: false
        entities:
          - entity: sensor.vmc_vel_target
            name: Velocità target
          - entity: sensor.vmc_vel_index
            name: Velocità attuale
          - entity: switch.vmc_vel_0
            name: Velocità 0
          - entity: switch.vmc_vel_1
            name: Velocità 1
          - entity: switch.vmc_vel_2
            name: Velocità 2
          - entity: switch.vmc_vel_3
            name: Velocità 3

      - type: entities
        title: "5 — Freecooling"
        show_header_toggle: false
        entities:
          - entity: binary_sensor.vmc_freecooling_candidate
            name: Candidato freecooling
          - entity: binary_sensor.vmc_freecooling_active
            name: Freecooling attivo

      - type: entities
        title: "6 — Finestre e ricambio consigliato"
        show_header_toggle: false
        entities:
          - entity: binary_sensor.windows_all_closed
            name: Casa chiusa
          - entity: sensor.clima_open_windows_recommended
            name: Apri finestre raccomandato

      - type: markdown
        title: "7 — Messaggi diagnostici"
        content: |
          {{ states('input_text.vent_messaggio_consiglio') }}
