title: "1 — Ventilazione"
icon: mdi:fan
views:
  - title: "VMC"
    icon: mdi:fan-auto
    path: vmc
    cards:
      - type: entities
        title: "Stato generale"
        show_header_toggle: false
        entities:
          - sensor.ventilation_priority
          - sensor.ventilation_reason
          - binary_sensor.vmc_sensori_critici_ok

      - type: entities
        title: "KPI aria"
        show_header_toggle: false
        entities:
          - sensor.t_in_media
          - sensor.ur_in_media
          - sensor.delta_t_in_out
          - sensor.delta_ah_in_out

      - type: entities
        title: "Controlli manuali"
        show_header_toggle: false
        entities:
          - input_select.vmc_mode
          - input_boolean.vmc_manual
          - input_select.vmc_manual_speed
          - input_boolean.vmc_boost_bagno

      - type: entities
        title: "Velocità reali"
        show_header_toggle: false
        entities:
          - sensor.vmc_vel_target
          - sensor.vmc_vel_index
          - switch.vmc_vel_0
          - switch.vmc_vel_1
          - switch.vmc_vel_2
          - switch.vmc_vel_3

      - type: entities
        title: "Freecooling"
        show_header_toggle: false
        entities:
          - binary_sensor.vmc_freecooling_candidate
          - binary_sensor.vmc_freecooling_attivo
          - sensor.vmc_freecooling_status

      - type: entities
        title: "Finestre"
        show_header_toggle: false
        entities:
          - binary_sensor.windows_all_closed
          - sensor.clima_open_windows_recommended

      - type: entities
        title: "Messaggi"
        show_header_toggle: false
        entities:
          - input_text.vent_messaggio_consiglio
