title: "1 Ventilazione (v2)"
views:
  - type: sections
    title: "VMC"
    path: climate_vmc_v2
    icon: mdi:fan
    # TODO: aggiungere badge stagione (caldo/freddo) quando esisterà un'entità canonica in MAP
    badges:
      - type: entity
        entity: sensor.t_out
        name: "T esterna"
        color: red
      - type: entity
        entity: sensor.ur_out
        name: "UR esterna"
        color: indigo
      - type: entity
        entity: binary_sensor.clima_ac_from_vmc_request
        name: "AC"
        icon: mdi:air-conditioner
        color: blue
      - type: entity
        entity: binary_sensor.heating_should_run
        name: "Riscaldamento"
        icon: mdi:radiator
        color: orange
    sections:
      - cards:
          - type: heading
            heading: "Stato generale"
            icon: mdi:fan
          - type: entities
            show_header_toggle: false
            entities:
              - entity: sensor.ventilation_priority
                name: "Priorità ventilazione"
              - entity: sensor.ventilation_reason
                name: "Motivo ventilazione"
              - entity: binary_sensor.vmc_sensors_ok
                name: "Sensori VMC ok"
              - entity: binary_sensor.clima_ac_from_vmc_request
                name: "Richiesta AC dal clima"
      - type: grid
        cards:
          - type: heading
            heading: "Zona giorno"
            icon: mdi:sofa
            badges:
              - type: entity
                entity: sensor.t_in_giorno
                name: "T zona giorno"
                color: red
              - type: entity
                entity: sensor.ur_in_giorno
                name: "UR zona giorno"
                color: indigo
          - type: tile
            entity: sensor.t_in_giorno
            name: "T zona giorno"
          - type: tile
            entity: sensor.ur_in_giorno
            name: "UR zona giorno"
          - type: tile
            entity: climate.ac_giorno
            name: AC Giorno
            state_content:
            - preset_mode
            - current_temperature
            vertical: false
            features:
            - type: target-temperature
            features_position: bottom
          - type: tile
            entity: binary_sensor.windows_giorno_any
            name: "Finestre zona giorno"
      - type: grid
        cards:
          - type: heading
            heading: "Zona notte"
            icon: mdi:bed
            badges:
              - type: entity
                entity: sensor.t_notte_med
                name: "T zona notte"
                color: red
              - type: entity
                entity: sensor.ur_notte_med
                name: "UR notte 1"
                color: indigo
          - type: tile
            entity: sensor.t_in_notte1
            name: "T zona notte1"
          - type: tile
            entity: sensor.ur_in_notte1
            name: "UR notte 1"
          - type: tile
            entity: sensor.t_in_notte2
            name: "T zona notte2"
          - type: tile
            entity: sensor.ur_in_notte2
            name: "UR notte 2"
          - type: tile
            entity: sensor.t_in_notte3
            name: "T zona notte2"
          - type: tile
            entity: sensor.ur_in_notte3
            name: "UR notte 3"      
          - type: tile
            entity: switch.ac_notte
            name: "AC notte"
          - type: tile
            entity: binary_sensor.windows_notte1
            name: "Finestre zona notte1"
          - type: tile
            entity: binary_sensor.windows_notte1
            name: "Finestre zona notte2"
          - type: tile
            entity: binary_sensor.windows_notte1
            name: "Finestre zona notte3"
      - type: grid
        cards:
          - type: heading
            heading: "Bagno"
            icon: mdi:shower
            badges:
              - type: entity
                entity: sensor.t_in_bagno
                name: "T bagno"
                color: red
              - type: entity
                entity: sensor.ur_in_bagno
                name: "UR bagno"
                color: indigo
          - type: tile
            entity: sensor.t_in_bagno
            name: "T bagno"
          - type: tile
            entity: sensor.ur_in_bagno
            name: "UR bagno"
          - type: tile
            entity: input_boolean.vmc_boost_bagno
            name: "Boost bagno"
          - type: tile
            entity: input_number.vmc_bagno_on
            name: "Soglia boost ON"
          - type: tile
            entity: input_number.vmc_bagno_off
            name: "Soglia boost OFF"
          # TODO: creare input_number soglia UR bagno per boost se serve helper dedicato
      - type: grid
        cards:
          - type: heading
            heading: "VMC & Freecooling"
            icon: mdi:fan-alert
          - type: tile
            entity: switch.vmc_vel_0
            name: "Vel 0"
          - type: tile
            entity: switch.vmc_vel_1
            name: "Vel 1"
          - type: tile
            entity: switch.vmc_vel_2
            name: "Vel 2"
          - type: tile
            entity: switch.vmc_vel_3
            name: "Vel 3"
          - type: tile
            entity: sensor.vmc_vel_target
            name: "Velocità target"
          - type: tile
            entity: sensor.vmc_vel_index
            name: "Indice velocità"
          - type: sensor
            entity: sensor.vmc_vel_target
            name: "Velocità target (24h)"
            graph: line
            hours_to_show: 24
            detail: 1
          - type: tile
            entity: binary_sensor.vmc_freecooling_candidate
            name: "Freecooling candidabile"
          - type: tile
            entity: binary_sensor.vmc_freecooling_active
            name: "Freecooling attivo"
          - type: tile
            entity: sensor.vmc_freecooling_status
            name: "Stato freecooling"
          - type: tile
            entity: sensor.t_in_med
            name: "T interna media"
          - type: tile
            entity: sensor.t_out
            name: "T esterna"

      - type: grid
        columns: 1
        cards:
          - type: heading
            heading: "Freecooling Passivhaus"
            icon: mdi:home-thermometer
          - type: tile
            entity: sensor.vmc_freecooling_status
            name: "Stato freecooling"
          - type: tile
            entity: sensor.delta_t_in_out
            name: "ΔT in-out"
          - type: tile
            entity: sensor.delta_ah_in_out
            name: "ΔAH in-out"
          - type: tile
            entity: sensor.clima_open_windows_recommended
            name: "Finestre consigliate"
      - type: grid
        cards:
          - type: heading
            heading: "Logica & trigger"
            icon: mdi:script-text-outline
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_select.vmc_mode
                name: "Modalità VMC"
              - entity: input_boolean.vmc_manual
                name: "Manuale abilitato"
              - entity: input_select.vmc_manual_speed
                name: "Velocità manuale"
              - entity: timer.vmc_manual_timeout
                name: "Timer manuale"
              - entity: binary_sensor.clima_ac_from_vmc_request
                name: "Richiesta AC dal clima"
              - entity: binary_sensor.vmc_bagno_boost_auto
                name: "Boost bagno auto"
              # TODO: aggiungere timer.vmc_boost_bagno se/ quando disponibile
          - type: markdown
            content: |
              ### Regole principali
              - **Boost bagno**: UR bagno > soglia ON per alcuni minuti, poi si spegne sotto soglia OFF.
              - **Freecooling**: T_in > 24°C **e** T_out < T_in **e** T_out > 20°C.
              - **Richiesta AC**: quando `binary_sensor.clima_ac_from_vmc_request` è ON, la logica VMC/AC richiede `AC giorno` o `AC notte`.
              - Riferimenti: logiche condivise in `logica/core/regole_core_logiche.md`, modulo in `logica/2_vmc/2_vmc.txt`, linee guida UI in `logica/core/regole_plancia.md`.
