title: "EcoHotWater (EHW)"
views:
  - title: "EHW"
    path: ehw
    icon: mdi:water-boiler
    type: sections
    max_columns: 3

    sections:
      - type: grid
        title: "Stato"
        cards:
          - type: entities
            title: "Stato"
            show_header_toggle: false
            entities:
              - entity: sensor.ehw_status
                name: Stato
              - entity: input_select.ehw_address_mode
                name: Address mode
              - entity: input_boolean.ehw_swap_top_bottom
                name: Swap top/bottom
          - type: entities
            title: "RAW debug"
            show_header_toggle: false
            entities:
              - entity: sensor.ehw_t01_raw
                name: T01 raw (selezionato)
              - entity: sensor.ehw_t02_raw
                name: T02 raw (selezionato)
              - entity: sensor.ehw_t03_raw
                name: T03 raw (selezionato)
              - entity: sensor.ehw_t04_raw
                name: T04 raw (selezionato)
              - entity: sensor.ehw_t05_raw
                name: T05 raw (selezionato)
              - entity: sensor.ehw_t06_raw
                name: T06 raw (selezionato)
              - entity: sensor.ehw_t02_raw_a
                name: T02 raw A
              - entity: sensor.ehw_t02_raw_b
                name: T02 raw B
              - entity: sensor.ehw_t03_raw_a
                name: T03 raw A
              - entity: sensor.ehw_t03_raw_b
                name: T03 raw B
              - entity: sensor.ehw_setpoint_raw_a
                name: Setpoint raw A (1104)
              - entity: sensor.ehw_setpoint_raw_b
                name: Setpoint raw B (1105)

      - type: grid
        title: "Temperature"
        cards:
          - type: entities
            title: "Sonde e delta"
            show_header_toggle: false
            entities:
              - entity: sensor.ehw_tank_top
                name: Tank top
              - entity: sensor.ehw_tank_bottom
                name: Tank bottom
              - entity: sensor.ehw_delta_stratificazione
                name: Delta stratificazione
          - type: history-graph
            title: "Temperature (24h)"
            hours_to_show: 24
            min_y: 20
            max_y: 80
            entities:
              - entity: sensor.ehw_tank_top
                name: Tank top
              - entity: sensor.ehw_tank_bottom
                name: Tank bottom
              - entity: sensor.ehw_setpoint
                name: Setpoint

      - type: grid
        title: "Setpoint & calibrazione"
        cards:
          - type: entities
            title: "Setpoint"
            show_header_toggle: false
            entities:
              - entity: sensor.ehw_setpoint
                name: Setpoint (°C)
              - entity: sensor.ehw_setpoint_raw
                name: Setpoint raw (selezionato)
              - entity: sensor.ehw_setpoint_raw_a
                name: Setpoint raw A (1104)
              - entity: sensor.ehw_setpoint_raw_b
                name: Setpoint raw B (1105)
          - type: entities
            title: "Calibrazione"
            show_header_toggle: false
            entities:
              - entity: input_number.ehw_temp_scale
                name: Temp scale
              - entity: input_number.ehw_temp_offset
                name: Temp offset
              - entity: input_number.ehw_setpoint_scale
                name: Setpoint scale
              - entity: input_number.ehw_setpoint_offset
                name: Setpoint offset
