title: "EcoHotWater (EHW)"
views:
  - title: "EHW"
    path: ehw
    icon: mdi:water-boiler
    type: sections
    max_columns: 2

    sections:
      - type: grid
        title: "Status"
        cards:
          - type: entities
            title: "Status word"
            show_header_toggle: false
            entities:
              - entity: sensor.ehw_status_word_hex
                name: Status word (hex)
                secondary_info: last-updated
              - entity: binary_sensor.ehw_status_bit_0100
                name: Bit 0x0100
              - entity: binary_sensor.ehw_status_bit_0200
                name: Bit 0x0200
              - entity: sensor.ehw_runtime_word_hex
                name: Runtime word (hex)
          - type: entities
            title: "Ultimo aggiornamento"
            show_header_toggle: false
            entities:
              - entity: sensor.ehw_reg56_status
                name: Reg56 status
                secondary_info: last-updated

      - type: grid
        title: "Debug"
        cards:
          - type: entities
            title: "Raw registers"
            show_header_toggle: false
            entities:
              - entity: sensor.ehw_reg56_status
                name: Reg56 status
              - entity: sensor.ehw_reg57_runtime
                name: Reg57 runtime
              - entity: sensor.ehw_reg60_value
                name: Reg60 value
          - type: history-graph
            title: "Reg56/Reg57 (24h)"
            hours_to_show: 24
            entities:
              - entity: sensor.ehw_reg56_status
                name: Reg56 status
              - entity: sensor.ehw_reg57_runtime
                name: Reg57 runtime
          - type: markdown
            title: "Note"
            content: |-
              Setpoint non esposto in chiaro; cambio setpoint riflette su reg56/reg57.
