title: "EcoHotWater (EHW)"
views:
  - title: "EHW"
    path: ehw
    icon: mdi:water-boiler
    type: sections
    max_columns: 3

    sections:
      - type: grid
        title: "Temperature"
        cards:
          - type: horizontal-stack
            cards:
              - type: entities
                title: "Scaled (°C)"
                entities:
                  - entity: sensor.ehw_tank_top
                    name: Tank top
                  - entity: sensor.ehw_tank_bottom
                    name: Tank bottom
                  - entity: sensor.ehw_setpoint
                    name: Setpoint
                  - entity: sensor.ehw_delta_stratificazione
                    name: Delta stratificazione

              - type: entities
                title: "RAW"
                entities:
                  - entity: sensor.ehw_t02_raw
                    name: T02 raw
                  - entity: sensor.ehw_t03_raw
                    name: T03 raw
                  - entity: sensor.ehw_setpoint_raw
                    name: Setpoint raw

          - type: history-graph
            title: "Temperature (24h)"
            hours_to_show: 24
            entities:
              - entity: sensor.ehw_tank_top
                name: Tank top
              - entity: sensor.ehw_tank_bottom
                name: Tank bottom
              - entity: sensor.ehw_setpoint
                name: Setpoint

      - type: grid
        title: "Calibrazione"
        cards:
          - type: entities
            title: "Calibrazione"
            show_header_toggle: false
            entities:
              - entity: input_number.ehw_temp_scale
                name: Temp scale
              - entity: input_number.ehw_temp_offset
                name: Temp offset
              - entity: input_number.ehw_setpoint_scale
                name: Setpoint scale
              - entity: input_number.ehw_setpoint_offset
                name: Setpoint offset
