title: "EcoHotWater (EHW)"
views:
  - title: "EHW"
    path: ehw
    icon: mdi:water-boiler
    type: sections
    max_columns: 3

    sections:
      - type: grid
        title: "Stato"
        cards:
          - type: entities
            title: "Stato operativo"
            show_header_toggle: false
            entities:
              - entity: binary_sensor.ehw_running
                name: In funzione
              - entity: sensor.ehw_status_word
                name: Status word
              - entity: sensor.ehw_status_word_1102_raw
                name: Status word 1102 (raw)
              - entity: sensor.ehw_status_word_1101_raw
                name: Status word 1101 (raw)
              - entity: sensor.ehw_last_update
                name: Ultimo update

          - type: gauge
            name: "Tank top"
            entity: sensor.ehw_tank_top
            min: 10
            max: 75
            severity:
              green: 40
              yellow: 55
              red: 65

      - type: grid
        title: "Temperature"
        cards:
          - type: entities
            title: "Sonde e delta"
            entities:
              - entity: sensor.ehw_tank_top
                name: Tank top
              - entity: sensor.ehw_tank_bottom
                name: Tank bottom
              - entity: sensor.ehw_tank_delta
                name: Delta stratificazione

          - type: history-graph
            title: "Temperature (24h)"
            hours_to_show: 24
            entities:
              - entity: sensor.ehw_tank_top
                name: Tank top
              - entity: sensor.ehw_tank_bottom
                name: Tank bottom
              - entity: sensor.ehw_setpoint
                name: Setpoint

          - type: statistics-graph
            title: "Delta stratificazione"
            chart_type: line
            period: hour
            days_to_show: 1
            stat_types:
              - mean
            entities:
              - entity: sensor.ehw_tank_delta
                name: Delta

      - type: grid
        title: "Setpoint & controllo"
        cards:
          - type: entities
            title: "Setpoint ACS"
            show_header_toggle: false
            entities:
              - entity: sensor.ehw_setpoint
                name: Setpoint attuale
              - entity: sensor.ehw_setpoint_raw
                name: Setpoint raw

          - type: entities
            title: "Modbus"
            show_header_toggle: false
            entities:
              - entity: input_number.ehw_slave_id
                name: Unit ID (slave)
