views:
  - title: "PV SolarEdge"
    path: pv_solaredge
    icon: mdi:solar-power
    type: sections
    max_columns: 3

    sections:

      #######################################################################
      # 1) STATO ATTUALE
      #######################################################################
      - type: grid
        title: "Stato attuale"
        cards:
          - type: gauge
            name: Potenza FV istantanea
            entity: sensor.pv_power_now
            min: 0
            max: 7000       # Impianto 6,7 kW – leggero margine
            needle: true

      #######################################################################
      # 2) ENERGIA
      #######################################################################
      - type: grid
        title: "Energia"
        cards:
          - type: entities
            title: "Produzione"
            entities:
              - entity: sensor.pv_energy_daily
                name: Oggi
              - entity: sensor.pv_energy_monthly
                name: Questo mese
              - entity: sensor.pv_energy_yearly
                name: Questo anno

      #######################################################################
      # 3) DEBUG (OPZIONALE)
      #######################################################################
      - type: grid
        title: "Debug sensori"
        cards:
          - type: entities
            entities:
              - entity: sensor.solaredge_potenza_attuale
                name: SolarEdge Potenza RAW
              - entity: sensor.solaredge_energia_dall_installazione
                name: SolarEdge Energia RAW
              - entity: sensor.pv_power_now
                name: PV Potenza canonico
              - entity: sensor.pv_energy_total
                name: PV Energia Totale
