#!/usr/bin/env python3
"""
Generate template binary_sensors that expose individual bits of the MIRAI
Modbus status word (register 4000) and status code (register 4001).

Usage:
    python mirai/dev/tools/mirai_generate_bit_sensors.py \
        --log-path /config/www/mirai/mirai_modbus_log.csv \
        --output mirai/runtime/20_templates.yaml

The log file is only used to validate that data collection is running; the
binary sensors reference the live raw sensors.
"""
from __future__ import annotations

import argparse
import pathlib
import sys
from typing import List

DEFAULT_LOG_PATH = "/config/www/mirai/mirai_modbus_log.csv"
DEFAULT_OUTPUT = "mirai/runtime/20_templates.yaml"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--log-path", default=DEFAULT_LOG_PATH, help="Path to the MIRAI Modbus CSV log")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Destination YAML file to generate")
    return parser.parse_args()


def build_sensor_lines() -> List[str]:
    lines: List[str] = []
    source_definitions = [
        ("word", "status word", "sensor.mirai_status_word_raw"),
        ("code", "status code", "sensor.mirai_status_code_raw"),
    ]

    lines.append("template:")
    lines.append("  - binary_sensor:")

    for slug, label, entity in source_definitions:
        lines.append(f"      # Bits extracted from {entity}")
        for bit in range(16):
            lines.append(f"      - name: \"MIRAI {label} bit {bit:02d}\"")
            lines.append(f"        unique_id: mirai_status_{slug}_bit_{bit:02d}")
            lines.append("        state: >-")
            lines.append(
                f"          {{{{ ((states('{entity}') | int(0)) >> {bit}) & 1 == 1 }}}}"
            )
    return lines


def main() -> None:
    args = parse_args()
    log_path = pathlib.Path(args.log_path)
    output_path = pathlib.Path(args.output)

    if not log_path.exists():
        print(f"[warning] Log file not found at {log_path}. Generation continues regardless.", file=sys.stderr)

    output_path.parent.mkdir(parents=True, exist_ok=True)

    header = [
        "# Auto-generated by tools/mirai_generate_bit_sensors.py",
        f"# Source log: {log_path}",
        "# Do not edit manually.",
    ]
    body = build_sensor_lines()
    output_path.write_text("\n".join(header + body) + "\n")
    print(f"Generated {output_path} with MIRAI bit binary_sensors.")


if __name__ == "__main__":
    main()
