binary_sensor:
  - platform: template
    sensors:
      climateops_ac_giorno_is_on:
        friendly_name: "AC Giorno Is On (proxy)"
        value_template: "{{ is_state('switch.ac_giorno','on') }}"
        availability_template: "{{ states('switch.ac_giorno') not in ['unknown','unavailable'] }}"
      climateops_ac_notte_is_on:
        friendly_name: "AC Notte Is On (proxy)"
        value_template: "{{ is_state('switch.ac_notte','on') }}"
        availability_template: "{{ states('switch.ac_notte') not in ['unknown','unavailable'] }}"
