title: "6 Energia"
views:
  - title: "Energia — Monitor"
    path: energia-monitor
    icon: mdi:solar-power
    type: sections
    max_columns: 3

    sections:
      - type: grid
        title: "Stato generale"
        cards:
          - type: glance
            title: "Direzione flussi"
            show_state: true
            entities:
              - entity: sensor.grid_direction
                name: Rete
              - entity: sensor.pv_direction
                name: FV

          - type: grid
            columns: 2
            square: false
            cards:
              - type: tile
                entity: sensor.grid_power_w
                name: Potenza rete
              - type: tile
                entity: sensor.pv_power_w
                name: Potenza FV

      - type: grid
        title: "KPI principali"
        cards:
          - type: grid
            columns: 2
            square: false
            cards:
              - type: tile
                entity: sensor.a_energia_prelevata_forward
                name: A — Prelevata
              - type: tile
                entity: sensor.a_energia_immessa_reverse
                name: A — Immessa
              - type: tile
                entity: sensor.b_energia_prelevata_forward
                name: B — Prelevata
              - type: tile
                entity: sensor.b_energia_immessa_reverse
                name: B — Immessa

      - type: grid
        title: "Grafici 24h / 7gg"
        cards:
          - type: history-graph
            title: "Potenza 24h"
            hours_to_show: 24
            refresh_interval: 60
            entities:
              - entity: sensor.pv_power_w
                name: FV [W]
              - entity: sensor.grid_power_w
                name: Rete [W]

          - type: history-graph
            title: "Direzioni 24h"
            hours_to_show: 24
            entities:
              - entity: sensor.grid_direction
                name: Rete
              - entity: sensor.pv_direction
                name: FV

          - type: statistics-graph
            title: "Bilancio 7 giorni"
            days_to_show: 7
            period: day
            chart_type: bar
            entities:
              - entity: sensor.a_energia_prelevata_forward
                name: A — Prelevata
              - entity: sensor.a_energia_immessa_reverse
                name: A — Immessa
              - entity: sensor.b_energia_prelevata_forward
                name: B — Prelevata
              - entity: sensor.b_energia_immessa_reverse
                name: B — Immessa

      - type: grid
        title: "Comandi e soglie"
        cards:
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_number.surplus_min_w
                name: Soglia surplus (W)
              - entity: input_number.surplus_lock_minutes
                name: Tempo lock (min)
              - entity: input_boolean.surplus_enable
                name: Surplus attivo
              - entity: input_boolean.energy_debug
                name: Debug energia

      - type: grid
        title: "Debug"
        cards:
          - type: entities
            entities:
              - sensor.grid_power_w
              - sensor.grid_direction
              - sensor.pv_power_w
              - sensor.pv_direction
              - sensor.a_energia_prelevata_forward
              - sensor.a_energia_immessa_reverse
              - sensor.b_energia_prelevata_forward
              - sensor.b_energia_immessa_reverse

  - title: "Energia FV"
    path: energia-fv
    icon: mdi:solar-panel-large
    type: panel
    cards:
      - type: vertical-stack
        cards:

          - type: entities
            title: "Stato FV"
            entities:
              - entity: sensor.pv_solaredge_lifetime_kwh_norm
                name: Energia dall'installazione
              - entity: sensor.pv_power_signed
                name: Potenza attuale

          # Grafico produzione giornaliera FV (derivato dal cumulativo)
          - type: custom:mini-graph-card
            name: "Produzione giornaliera FV"
            icon: mdi:solar-power
            hours_to_show: 168
            points_per_hour: 1
            show:
              graph: bar
              labels: true
              legend: false
            unit: kWh
            entities:
              - entity: sensor.pv_solaredge_lifetime_kwh_norm
                name: "Produzione"
                show_state: false
                unit: kWh
                transform: "return x;"
                group_by: date
                aggregate_func: diff

          # Grafico potenza FV in tempo reale
          - type: custom:mini-graph-card
            name: "Potenza FV (oggi)"
            icon: mdi:flash
            hours_to_show: 24
            points_per_hour: 6
            show:
              graph: line
              labels: true
              legend: false
            entities:
              - entity: sensor.pv_power_signed
                name: "Potenza"
