sensor:
  - platform: template
    sensors:
      climateops_kpi_vmc_baseline_ratio:
        friendly_name: "KPI VMC Baseline Ratio"
        unit_of_measurement: "%"
        value_template: >
          {{ (states('sensor.vmc_baseline_ratio') | float(0)) }}
        availability_template: >
          {{ states('sensor.vmc_baseline_ratio') not in ['unknown','unavailable'] }}

      climateops_kpi_heating_cycles_day:
        friendly_name: "KPI Heating Cycles / Day"
        unit_of_measurement: "cycles"
        value_template: >
          {{ (states('sensor.heating_cycles_day') | float(0)) }}
        availability_template: >
          {{ states('sensor.heating_cycles_day') not in ['unknown','unavailable'] }}
