###############################################################################
# /config/packages/6_energy_surplus.yaml
# Bilanci FV/Rete/Casa + Surplus + KPI giornalieri (usa sensori *norm*)
# Include helper dedicati a soglie surplus e flag debug.
###############################################################################

homeassistant:
  customize_glob:
    "sensor.grid_*":
      device_class: power
      state_class: measurement
      unit_of_measurement: W
    "sensor.pv_*":
      device_class: power
      state_class: measurement
      unit_of_measurement: W
    "sensor.energy_*_daily":
      device_class: energy
      state_class: total_increasing
      unit_of_measurement: kWh

# =========================
# Helper per soglie e debug
# =========================
input_boolean:
  surplus_enable:
    name: "Surplus — automazioni attive"
    icon: mdi:solar-power
  energy_debug:
    name: "Energia — debug avanzato"
    icon: mdi:bug

input_number:
  surplus_min_w:
    name: "Surplus — soglia minima (W)"
    min: 0
    max: 5000
    step: 50
    unit_of_measurement: "W"
    icon: mdi:ray-start-vertex-end
  surplus_lock_minutes:
    name: "Surplus — lock automazioni (min)"
    min: 0
    max: 240
    step: 5
    unit_of_measurement: "min"
    icon: mdi:timer-lock

# 1) DERIVATIVE (kW) – fonti normalizzate da packages/energy.yaml
sensor:
  - platform: derivative
    name: a_power_import_kw
    source: sensor.a_pre_kwh_norm
    unit_time: h
    round: 3
    unit: kW

  - platform: derivative
    name: a_power_export_kw
    source: sensor.a_imm_kwh_norm
    unit_time: h
    round: 3
    unit: kW

  - platform: derivative
    name: b_power_forward_kw
    source: sensor.b_pre_kwh_norm
    unit_time: h
    round: 3
    unit: kW

  - platform: derivative
    name: b_power_reverse_kw
    source: sensor.b_imm_kwh_norm
    unit_time: h
    round: 3
    unit: kW

# 2) TEMPLATE: potenze W, bilanci, KPI %, sentinella e binary
template:
  - sensor:
      # Rete (W)
      - name: grid_power_import
        unit_of_measurement: W
        state: "{{ (states('sensor.a_power_import_kw')|float(0) * 1000) | round(0) }}"
      - name: grid_power_export
        unit_of_measurement: W
        state: "{{ (states('sensor.a_power_export_kw')|float(0) * 1000) | round(0) }}"
      - name: grid_power_signed
        unit_of_measurement: W
        state: "{{ (states('sensor.grid_power_import')|float(0) - states('sensor.grid_power_export')|float(0)) | round(0) }}"
        attributes:
          note: ">0 import, <0 export"

      # FV (W)
      - name: pv_power_forward
        unit_of_measurement: W
        state: "{{ (states('sensor.b_power_forward_kw')|float(0) * 1000) | round(0) }}"
      - name: pv_power_reverse
        unit_of_measurement: W
        state: "{{ (states('sensor.b_power_reverse_kw')|float(0) * 1000) | round(0) }}"
      - name: pv_power_signed
        unit_of_measurement: W
        state: "{{ (states('sensor.pv_power_forward')|float(0) - states('sensor.pv_power_reverse')|float(0)) | round(0) }}"
        attributes:
          note: ">0 produzione FV verso casa"

      # Casa + Surplus (W)
      - name: house_power
        unit_of_measurement: W
        state: >-
          {% set pv  = states('sensor.pv_power_signed')|float(0) %}
          {% set imp = max(states('sensor.grid_power_signed')|float(0), 0) %}
          {% set exp = (states('sensor.grid_power_signed')|float(0) < 0)
                        | iif(states('sensor.grid_power_signed')|float(0) * -1, 0) %}
          {{ (pv + imp - exp) | round(0) }}
        attributes:
          formula: "house = pv + import - export"

      - name: surplus_power
        unit_of_measurement: W
        state: >-
          {% set pv = states('sensor.pv_power_signed')|float(0) %}
          {% set h  = states('sensor.house_power')|float(0) %}
          {{ max(pv - h, 0) | round(0) }}

      # KPI energia giorno (kWh)
      - name: energy_house_daily
        unit_of_measurement: kWh
        state: >-
          {% set pv = states('sensor.energy_pv_daily')|float(0) %}
          {% set imp = states('sensor.energy_import_daily')|float(0) %}
          {% set exp = states('sensor.energy_export_daily')|float(0) %}
          {{ (pv + imp - exp) | round(3) }}

      - name: energy_pv_used_daily
        unit_of_measurement: kWh
        state: >-
          {% set pv = states('sensor.energy_pv_daily')|float(0) %}
          {% set exp = states('sensor.energy_export_daily')|float(0) %}
          {{ max(pv - exp, 0) | round(3) }}

      - name: autoconsumo_percent
        unit_of_measurement: "%"
        state: >-
          {% set pv = states('sensor.energy_pv_daily')|float(0) %}
          {% set used = states('sensor.energy_pv_used_daily')|float(0) %}
          {% if pv > 0 %}{{ (used/pv*100)|round(1) }}{% else %}0{% endif %}

      - name: autosufficienza_percent
        unit_of_measurement: "%"
        state: >-
          {% set house = states('sensor.energy_house_daily')|float(0) %}
          {% set used  = states('sensor.energy_pv_used_daily')|float(0) %}
          {% if house > 0 %}{{ (used/house*100)|round(1) }}{% else %}0{% endif %}

      - name: energy_surplus_package_ok
        state: "ok"

    binary_sensor:
      - name: surplus_ok
        unique_id: surplus_ok
        device_class: power
        state: >-
          {% set thr = states('input_number.surplus_min_w')|float(700) %}
          {% set s = states('sensor.surplus_power')|float(0) %}
          {{ s >= thr }}
        icon: >-
          {% if is_state('binary_sensor.surplus_ok','on') %}
            mdi:solar-power
          {% else %}
            mdi:power-plug-off-outline
          {% endif %}
        attributes:
          soglia_w: "{{ states('input_number.surplus_min_w') }}"
          surplus_attuale: "{{ states('sensor.surplus_power') }}"

# 3) Utility meter giornalieri (kWh) — su letture normalizzate
utility_meter:
  energy_import_daily:
    source: sensor.a_pre_kwh_norm
    cycle: daily
  energy_export_daily:
    source: sensor.a_imm_kwh_norm
    cycle: daily
  energy_pv_daily:
    source: sensor.b_pre_kwh_norm
    cycle: daily
