---
###############################################################################
# 3_ac.yaml — Controllo Aria Condizionata (Passivhaus-Oriented)
# Controller unico AC con priorità, hook VMC e telemetria
###############################################################################

# -----------------------------------------------------------------------------
# PRIORITÀ AC (P0–P4)
# -----------------------------------------------------------------------------
# P0) Failsafe sensori → spegni AC.
# P1) Block da VMC / anti-secco → AC vietata.
# P2) DRY (deumidifica) → UR alta, T_in non troppo bassa.
# P3) COOL (raffrescamento comfort) → T_in > setpoint, solo in stagione calda.
# P4) Idle → tutto OFF.

# ============================================================================
# 1) HELPER INPUTS — soglie, timer, blocchi
# ============================================================================
input_number:
  # Nuovi helper uniformati alla nuova architettura
  ac_cool_setpoint:
    name: "AC — setpoint COOL (°C)"
    min: 22
    max: 28
    step: 0.5
    unit_of_measurement: "°C"

  ac_dry_ur_on:
    name: "AC — UR ON (DRY) %"
    min: 50
    max: 80
    step: 1
    unit_of_measurement: "%"

  ac_dry_ur_off:
    name: "AC — UR OFF (DRY) %"
    min: 40
    max: 75
    step: 1
    unit_of_measurement: "%"

  ac_min_on_minutes:
    name: "AC — Min ON (min)"
    min: 5
    max: 120
    step: 5
    unit_of_measurement: "min"

  ac_min_off_minutes:
    name: "AC — Min OFF (min)"
    min: 5
    max: 120
    step: 5
    unit_of_measurement: "min"

input_boolean:
  ac_manual:
    name: "AC — Manuale attivo"
    icon: mdi:hand-back-right

  ac_block_vmc:
    name: "AC — Block da VMC"
    icon: mdi:fan-off

input_select:
  ac_manual_mode:
    name: "AC — Modalità manuale"
    options: ["OFF", "DRY", "COOL"]
    icon: mdi:tune-variant

timer:
  ac_manual_timeout:
    name: "AC — Timeout manuale"
    duration: "01:00:00"

  ac_block_vmc_timeout:
    name: "AC — Timeout block VMC"
    duration: "00:30:00"

# ============================================================================
# 2) TEMPLATE — failsafe, blocchi, telemetria e diagnostica
# ============================================================================
template:
  - binary_sensor:
      - name: "AC — Failsafe sensori"
        unique_id: ac_failsafe_sensors_bad
        device_class: problem
        state: >
          {% set sensors = {
            'sensor.t_in_med': (-20, 50),
            'sensor.t_out': (-30, 60),
            'sensor.ur_in_media': (0, 100),
            'sensor.ur_out': (0, 100)
          } %}
          {% set bad = false %}
          {% for sid, limits in sensors.items() %}
            {% if bad %}{% break %}{% endif %}
            {% if sid in states %}
              {% set ent = states[sid] %}
              {% if ent.state in ['unknown','unavailable',''] %}
                {% set bad = true %}
              {% else %}
                {% set lo = limits[0] %}
                {% set hi = limits[1] %}
                {% set val = ent.state | float(0) %}
                {% if val < lo or val > hi %}
                  {% set bad = true %}
                {% endif %}
              {% endif %}
            {% else %}
              {% set bad = true %}
            {% endif %}
          {% endfor %}
          {{ bad }}

      - name: "Stagione calda attiva"
        unique_id: stagione_calda
        device_class: heat
        state: >-
          {% set stagione = states('sensor.vent_stagione') %}
          {% if stagione in ['estate','inverno'] %}
            {{ stagione == 'estate' }}
          {% else %}
            {% set m = now().month %}
            {{ m in [5,6,7,8,9] }}
          {% endif %}

      - name: "AC — Block by VMC"
        unique_id: ac_block_by_vmc
        state: "{{ is_state('input_boolean.ac_block_vmc','on') }}"

      - name: "AC — Lock min ON OK"
        unique_id: ac_lock_min_on_ok
        state: >
          {% set mins = states('input_number.ac_min_on_minutes') | float(15) %}
          {% set entities = ['switch.ac_giorno', 'switch.ac_notte'] %}
          {% for ent_id in entities %}
            {% if ent_id in states %}
              {% set s = states[ent_id] %}
              {% if s.state == 'on' and (now() - s.last_changed).total_seconds() / 60 < mins %}
                {{ false }}
              {% endif %}
            {% endif %}
          {% endfor %}
          true

      - name: "AC — Lock min OFF OK"
        unique_id: ac_lock_min_off_ok
        state: >
          {% set mins = states('input_number.ac_min_off_minutes') | float(15) %}
          {% set entities = ['switch.ac_giorno', 'switch.ac_notte'] %}
          {% for ent_id in entities %}
            {% if ent_id in states %}
              {% set s = states[ent_id] %}
              {% if s.state == 'off' and (now() - s.last_changed).total_seconds() / 60 < mins %}
                {{ false }}
              {% endif %}
            {% endif %}
          {% endfor %}
          true

  - sensor:
      - name: "AC Priority"
        unique_id: ac_priority
        icon: mdi:arrow-top-right-bold-outline
        state: "{{ (state_attr('sensor.ac_reason','priority')) if state_attr('sensor.ac_reason','priority') not in [none, ''] else 'idle' }}"
        attributes:
          reason: "{{ state_attr('sensor.ac_reason','reason') }}"
          mode: "{{ state_attr('sensor.ac_reason','mode') }}"
          target: "{{ state_attr('sensor.ac_reason','target') }}"

      - name: "AC Reason"
        unique_id: ac_reason
        icon: mdi:text
        state: "{{ state_attr('sensor.ac_reason','priority') if state_attr('sensor.ac_reason','priority') not in [none, ''] else 'idle' }}"
        attributes:
          priority: "{{ state_attr('sensor.ac_reason','priority') or 'idle' }}"
          reason: "{{ state_attr('sensor.ac_reason','reason') or '—' }}"
          mode: "{{ state_attr('sensor.ac_reason','mode') or 'off' }}"
          target: "{{ state_attr('sensor.ac_reason','target') or 'none' }}"

  # Ultimi ON/OFF (trigger-based) Giorno/Notte
  - trigger:
      - platform: state
        entity_id: switch.ac_giorno
        to: "on"
    sensor:
      - name: "AC Giorno — Ultimo ON"
        unique_id: ac_giorno_ultimo_on
        device_class: timestamp
        state: "{{ now().isoformat() }}"

  - trigger:
      - platform: state
        entity_id: switch.ac_giorno
        to: "off"
    sensor:
      - name: "AC Giorno — Ultimo OFF"
        unique_id: ac_giorno_ultimo_off
        device_class: timestamp
        state: "{{ now().isoformat() }}"

  - trigger:
      - platform: state
        entity_id: switch.ac_notte
        to: "on"
    sensor:
      - name: "AC Notte — Ultimo ON"
        unique_id: ac_notte_ultimo_on
        device_class: timestamp
        state: "{{ now().isoformat() }}"

  - trigger:
      - platform: state
        entity_id: switch.ac_notte
        to: "off"
    sensor:
      - name: "AC Notte — Ultimo OFF"
        unique_id: ac_notte_ultimo_off
        device_class: timestamp
        state: "{{ now().isoformat() }}"

# ============================================================================
# 3) AUTOMAZIONI — hook VMC + controller unico priorità
# ============================================================================
automation:
  - id: ac_hook_block_from_vmc
    alias: "AC — Hook: block da VMC"
    mode: restart
    trigger:
      - platform: event
        event_type: hook_vmc_request_ac_block
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.ac_block_vmc
      - service: timer.start
        target:
          entity_id: timer.ac_block_vmc_timeout

  - id: ac_hook_block_timeout_clear
    alias: "AC — Hook: clear block VMC dopo timeout"
    mode: restart
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.ac_block_vmc_timeout
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.ac_block_vmc

  - id: ac_controller_priority
    alias: "AC — Controllo priorità P0–P4"
    mode: restart
    trigger:
      - platform: time_pattern
        minutes: "/3"
      - platform: state
        entity_id:
          - binary_sensor.ac_failsafe_sensors_bad
          - binary_sensor.ac_block_by_vmc
          - binary_sensor.stagione_calda
          - binary_sensor.ac_lock_min_on_ok
          - binary_sensor.ac_lock_min_off_ok
          - sensor.t_in_med
          - sensor.t_out
          - sensor.ur_in_media
          - sensor.ur_out
          - switch.ac_giorno
          - switch.ac_notte
          - input_boolean.ac_manual
          - input_select.ac_manual_mode
    action:
      - variables:
          Tin: "{{ states('sensor.t_in_med')|float(0) }}"
          Tout: "{{ states('sensor.t_out')|float(0) }}"
          URin: "{{ states('sensor.ur_in_media')|float(0) }}"
          URout: "{{ states('sensor.ur_out')|float(0) }}"
          set_cool: "{{ states('input_number.ac_cool_setpoint')|float(25) }}"
          ur_on: "{{ states('input_number.ac_dry_ur_on')|float(65) }}"
          ur_off: "{{ states('input_number.ac_dry_ur_off')|float(55) }}"
          stagione_calda: "{{ is_state('binary_sensor.stagione_calda','on') }}"
          manual_on: "{{ is_state('input_boolean.ac_manual','on') }}"
          manual_mode: "{{ states('input_select.ac_manual_mode') }}"

      - choose:
          # Manuale: non toccare nulla
          - conditions:
              - condition: template
                value_template: "{{ manual_on and manual_mode != 'OFF' }}"
            sequence:
              - event: template_event
                event_data:
                  entity_id: sensor.ac_reason
                  attributes:
                    priority: "manual"
                    reason: "Controllo manuale attivo ({{ manual_mode }})"
                    mode: "{{ manual_mode | lower }}"
                    target: "manual"
              - stop: "Manuale attivo"

          # P0 - Failsafe sensori
          - conditions:
              - condition: state
                entity_id: binary_sensor.ac_failsafe_sensors_bad
                state: "on"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id:
                    - switch.ac_giorno
                    - switch.ac_notte
              - event: template_event
                event_data:
                  entity_id: sensor.ac_reason
                  attributes:
                    priority: "P0_failsafe"
                    reason: "Sensori non validi"
                    mode: "off"
                    target: "none"
              - stop: "Failsafe attivo"

          # P1 - Block da VMC / anti-secco
          - conditions:
              - condition: state
                entity_id: binary_sensor.ac_block_by_vmc
                state: "on"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id:
                    - switch.ac_giorno
                    - switch.ac_notte
              - event: template_event
                event_data:
                  entity_id: sensor.ac_reason
                  attributes:
                    priority: "P1_block_vmc"
                    reason: "Blocco da VMC (anti-secco / richiesta impianto)"
                    mode: "off"
                    target: "none"
              - stop: "Block VMC attivo"

          # Lock min ON: lascia correre finché non scade il timer minimo
          - conditions:
              - condition: template
                value_template: >
                  {{ (is_state('switch.ac_giorno','on') or is_state('switch.ac_notte','on'))
                     and not is_state('binary_sensor.ac_lock_min_on_ok','on') }}
            sequence:
              - event: template_event
                event_data:
                  entity_id: sensor.ac_reason
                  attributes:
                    priority: "lock_min_on"
                    reason: "Vincolo min ON in corso"
                    mode: "hold"
                    target: "hold"
              - stop: "Min ON ancora attivo"

          # P2 - DRY (umidità alta)
          - conditions:
              - condition: template
                value_template: >
                  {{ URin > ur_on and URout < URin and Tin > 20 }}
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.ac_notte
              - service: switch.turn_off
                target:
                  entity_id: switch.ac_giorno
              - event: template_event
                event_data:
                  entity_id: sensor.ac_reason
                  attributes:
                    priority: "P2_dry"
                    reason: "UR interna alta ({{ URin }}%)"
                    mode: "dry"
                    target: "notte"
              - event: hook_ac_request_vmc_low
                event_data:
                  source: "ac_controller"
                  mode: "dry"
              - stop: "DRY attivo"

          # P3 - COOL (comfort) solo stagione calda
          - conditions:
              - condition: template
                value_template: >
                  {{ stagione_calda and Tin > (set_cool + 0.5) }}
              - condition: state
                entity_id: binary_sensor.ac_lock_min_off_ok
                state: "on"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.ac_giorno
              - service: switch.turn_off
                target:
                  entity_id: switch.ac_notte
              - event: template_event
                event_data:
                  entity_id: sensor.ac_reason
                  attributes:
                    priority: "P3_cool"
                    reason: "Tin {{ Tin }}°C > set_cool {{ set_cool }}°C"
                    mode: "cool"
                    target: "giorno"
              - event: hook_ac_request_vmc_low
                event_data:
                  source: "ac_controller"
                  mode: "cool"
              - stop: "COOL attivo"

      - service: switch.turn_off
        target:
          entity_id:
            - switch.ac_giorno
            - switch.ac_notte
      - event: template_event
        event_data:
          entity_id: sensor.ac_reason
          attributes:
            priority: "idle"
            reason: "Nessuna condizione AC attiva"
            mode: "off"
            target: "none"

# ============================================================================
# 4) CONTATORI RUN-TIME & CICLI (oggi) — separati per Giorno/Notte
# ============================================================================
sensor:
  # === AC GIORNO ===
  - platform: history_stats
    name: "AC Giorno — Tempo ON oggi"
    unique_id: ac_giorno_tempo_on_oggi
    entity_id: switch.ac_giorno
    state: "on"
    type: time
    start: "{{ today_at() }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: "AC Giorno — Cicli ON oggi"
    unique_id: ac_giorno_cicli_on_oggi
    entity_id: switch.ac_giorno
    state: "on"
    type: count
    start: "{{ today_at() }}"
    end: "{{ now() }}"

  # === AC NOTTE ===
  - platform: history_stats
    name: "AC Notte — Tempo ON oggi"
    unique_id: ac_notte_tempo_on_oggi
    entity_id: switch.ac_notte
    state: "on"
    type: time
    start: "{{ today_at() }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: "AC Notte — Cicli ON oggi"
    unique_id: ac_notte_cicli_on_oggi
    entity_id: switch.ac_notte
    state: "on"
    type: count
    start: "{{ today_at() }}"
    end: "{{ now() }}"

# ============================================================================
# LEGACY AUTOMATIONS — disattivate a favore del controller unico
# ============================================================================
#  - alias: "AC Giorno - controllo DRY/COOL"
#    id: ac_giorno_control
#    trigger:
#      - platform: time_pattern
#        minutes: "/1"
#      - platform: state
#        entity_id:
#          - sensor.t_in_giorno
#          - sensor.ur_in_giorno
#          - binary_sensor.ac_need_cool
#          - binary_sensor.ac_need_dry
#    condition:
#      - condition: state
#        entity_id: binary_sensor.vmc_dry_active
#        state: "off"
#      - condition: state
#        entity_id: binary_sensor.ac_blocco_notte
#        state: "off"
#    action:
#      - choose:
#          - conditions:
#              - condition: state
#                entity_id: binary_sensor.ac_should_run
#                state: "on"
#            sequence:
#              - service: switch.turn_on
#                target:
#                  entity_id: switch.ac_giorno
#          - conditions:
#              - condition: state
#                entity_id: binary_sensor.ac_should_run
#                state: "off"
#            sequence:
#              - service: switch.turn_off
#                target:
#                  entity_id: switch.ac_giorno

#  - alias: "AC Notte - blocco forzato"
#    id: ac_notte_block
#    trigger:
#      - platform: time_pattern
#        minutes: "/10"
#    condition: []
#    action:
#      - service: switch.turn_off
#        target:
#          entity_id:
#            - switch.ac_notte
#            - switch.ac_giorno
