---
# =========================
# 5_powermeter.yaml – CLEAN
# Helpers + Utility Meter + Statistics per plancia "5 consumi – Core"
# Nessun wrapper top-level, nessuna lista con "- name:". Solo mapping con entity_id univoci.
# =========================

# --- HELPERS -------------------------------------------------
input_number:
  pm2_on_w:
    name: Lavatrice – soglia ON (W)
    min: 0
    max: 3000
    step: 5
    unit_of_measurement: W
    mode: slider
  pm2_off_w:
    name: Lavatrice – soglia OFF (W)
    min: 0
    max: 3000
    step: 5
    unit_of_measurement: W
    mode: slider
  pm2_min_run_min:
    name: Lavatrice – durata minima ciclo (min)
    min: 0
    max: 180
    step: 1
    unit_of_measurement: min
    mode: slider

  pm3_on_w:
    name: Asciugatrice – soglia ON (W)
    min: 0
    max: 3000
    step: 5
    unit_of_measurement: W
    mode: slider
  pm3_off_w:
    name: Asciugatrice – soglia OFF (W)
    min: 0
    max: 3000
    step: 5
    unit_of_measurement: W
    mode: slider
  pm3_min_run_min:
    name: Asciugatrice – durata minima ciclo (min)
    min: 0
    max: 180
    step: 1
    unit_of_measurement: min
    mode: slider

  pm1_on_w:
    name: Romeo – soglia ON (W)
    min: 0
    max: 3000
    step: 5
    unit_of_measurement: W
    mode: slider
  pm1_off_w:
    name: Romeo – soglia OFF (W)
    min: 0
    max: 3000
    step: 5
    unit_of_measurement: W
    mode: slider
  pm1_min_run_min:
    name: Romeo – durata minima ciclo (min)
    min: 0
    max: 180
    step: 1
    unit_of_measurement: min
    mode: slider

  # KPI ultimo ciclo (scritti da automazioni)
  pm2_last_cycle_kwh:
    name: Lavatrice – kWh ultimo ciclo
    min: 0
    max: 20
    step: 0.001
    unit_of_measurement: kWh
    mode: box
  pm3_last_cycle_kwh:
    name: Asciugatrice – kWh ultimo ciclo
    min: 0
    max: 20
    step: 0.001
    unit_of_measurement: kWh
    mode: box
  pm1_last_cycle_kwh:
    name: Romeo – kWh ultimo ciclo
    min: 0
    max: 20
    step: 0.001
    unit_of_measurement: kWh
    mode: box

input_datetime:
  pm2_last_start:
    name: Lavatrice – ultimo start
    has_date: true
    has_time: true
  pm2_last_stop:
    name: Lavatrice – ultimo stop
    has_date: true
    has_time: true
  pm3_last_start:
    name: Asciugatrice – ultimo start
    has_date: true
    has_time: true
  pm3_last_stop:
    name: Asciugatrice – ultimo stop
    has_date: true
    has_time: true
  pm1_last_start:
    name: Romeo – ultimo start
    has_date: true
    has_time: true
  pm1_last_stop:
    name: Romeo – ultimo stop
    has_date: true
    has_time: true

# (opzionale) contatori eventi ciclo
counter:
  pm2_cycles:
    name: Lavatrice – conteggio cicli
    step: 1
    restore: true
  pm3_cycles:
    name: Asciugatrice – conteggio cicli
    step: 1
    restore: true
  pm1_cycles:
    name: Romeo – conteggio cicli
    step: 1
    restore: true

# --- UTILITY METER (kWh giorno/mese) -------------------------
utility_meter:
  pm2_energy_daily:
    source: sensor.pm2_mss310_energy_kwh_main_channel
    cycle: daily
  pm2_energy_monthly:
    source: sensor.pm2_mss310_energy_kwh_main_channel
    cycle: monthly

  pm3_energy_daily:
    source: sensor.pm3_mss310_energy_kwh_main_channel
    cycle: daily
  pm3_energy_monthly:
    source: sensor.pm3_mss310_energy_kwh_main_channel
    cycle: monthly

  pm1_energy_daily:
    source: sensor.pm1_mss310_energy_kwh_main_channel
    cycle: daily
  pm1_energy_monthly:
    source: sensor.pm1_mss310_energy_kwh_main_channel
    cycle: monthly

# --- STATISTICS (medie/picchi per plancia) -------------------
sensor:
  - platform: statistics
    name: pm2_power_mean_15m
    entity_id: sensor.pm2_mss310_power_w_main_channel
    state_characteristic: mean
    sampling_size: 200
    max_age:
      minutes: 15
  - platform: statistics
    name: pm2_power_max_24h
    entity_id: sensor.pm2_mss310_power_w_main_channel
    state_characteristic: value_max
    sampling_size: 5000
    max_age:
      hours: 24

  - platform: statistics
    name: pm3_power_mean_15m
    entity_id: sensor.pm3_mss310_power_w_main_channel
    state_characteristic: mean
    sampling_size: 200
    max_age:
      minutes: 15
  - platform: statistics
    name: pm3_power_max_24h
    entity_id: sensor.pm3_mss310_power_w_main_channel
    state_characteristic: value_max
    sampling_size: 5000
    max_age:
      hours: 24

  - platform: statistics
    name: pm1_power_mean_15m
    entity_id: sensor.pm1_mss310_power_w_main_channel
    state_characteristic: mean
    sampling_size: 200
    max_age:
      minutes: 15
  - platform: statistics
    name: pm1_power_max_24h
    entity_id: sensor.pm1_mss310_power_w_main_channel
    state_characteristic: value_max
    sampling_size: 5000
    max_age:
      hours: 24

# --- FRIENDLY NAMES (coerenza UI) ----------------------------
homeassistant:
  customize:
    sensor.pm1_energy_daily: {friendly_name: "Romeo - kWh / giorno"}
    sensor.pm1_energy_monthly: {friendly_name: "Romeo - kWh / mese"}
    sensor.pm2_energy_daily: {friendly_name: "Lavatrice - kWh / giorno"}
    sensor.pm2_energy_monthly: {friendly_name: "Lavatrice - kWh / mese"}
    sensor.pm3_energy_daily: {friendly_name: "Asciugatrice - kWh / giorno"}
    sensor.pm3_energy_monthly: {friendly_name: "Asciugatrice - kWh / mese"}


# --- TEMPLATE: ore ON oggi (per KPI plancia) -----------------
template:
  - sensor:
      - name: "Lavatrice – h ON oggi"
        unique_id: pm2_on_time_today
        unit_of_measurement: "h"
        icon: mdi:timer-outline
        state: >
          {{ (states('sensor.pm2_in_ciclo_today') | float(0)) | round(2) }}

      - name: "Asciugatrice – h ON oggi"
        unique_id: pm3_on_time_today
        unit_of_measurement: "h"
        icon: mdi:timer-outline
        state: >
          {{ (states('sensor.pm3_in_ciclo_today') | float(0)) | round(2) }}

      - name: "Romeo – h ON oggi"
        unique_id: pm1_on_time_today
        unit_of_measurement: "h"
        icon: mdi:timer-outline
        state: >
          {{ (states('sensor.pm1_in_ciclo_today') | float(0)) | round(2) }}
