# MIRAI package router
input_boolean: !include mirai/00_input_boolean.yaml
shell_command: !include mirai/00_shell_command.yaml
modbus: !include mirai/10_modbus.yaml
template: !include mirai/20_templates.yaml
notify: !include mirai/25_notify.yaml
automation: !include mirai/30_automations.yaml
