input_boolean: !include packages/mirai/00_globals_input_boolean.yaml
input_number: !include packages/mirai/00_globals_input_number.yaml

modbus: !include packages/mirai/10_modbus.yaml
template: !include packages/mirai/20_templates.yaml
automation: !include packages/mirai/30_automations.yaml
