input_boolean: !include mirai/00_input_boolean.yaml
shell_command: !include mirai/01_shell_command.yaml
modbus: !include mirai/10_modbus.yaml
template: !include mirai/20_templates.yaml
automation: !include mirai/30_automations.yaml
