input_boolean: !include ../mirai/runtime/00_input_boolean.yaml
shell_command: !include ../mirai/runtime/01_shell_command.yaml
modbus: !include ../mirai/runtime/10_modbus.yaml
template: !include ../mirai/runtime/20_templates.yaml
automation: !include ../mirai/runtime/30_automations.yaml
