automation:
  - alias: "Climate debug – Telegram notifications"
    id: climate_debug_telegram_notifications
    mode: queued
    trigger:
      - platform: state
        entity_id:
          - sensor.ventilation_priority
          - sensor.heating_priority
          - sensor.ac_priority
    condition:
      - condition: state
        entity_id: input_boolean.climate_debug_telegram
        state: "on"
    variables:
      entity: "{{ trigger.entity_id }}"
      old: "{{ trigger.from_state.state if trigger.from_state is not none else 'unknown' }}"
      new: "{{ trigger.to_state.state if trigger.to_state is not none else 'unknown' }}"
      subsystem: >-
        {% if trigger.entity_id == 'sensor.ventilation_priority' %}
          Ventilation
        {% elif trigger.entity_id == 'sensor.heating_priority' %}
          Heating
        {% elif trigger.entity_id == 'sensor.ac_priority' %}
          AC
        {% else %}
          Climate
        {% endif %}
      reason: >-
        {% if trigger.entity_id == 'sensor.ventilation_priority' %}
          {{ states('sensor.ventilation_state_reason') }}
        {% elif trigger.entity_id == 'sensor.heating_priority' %}
          {{ states('sensor.heating_state_reason') }}
        {% elif trigger.entity_id == 'sensor.ac_priority' %}
          {{ states('sensor.ac_state_reason') }}
        {% else %}
          {{ states(trigger.entity_id) }}
        {% endif %}
    action:
      - service: notify.telegram_davide
        data:
          message: |
            [CLIMATE][{{ subsystem }}]
            {{ old }} – {{ new }}
            Reason: {{ reason }}
            Entity: {{ entity }}
            Time: {{ now() }}
